### ISSUE TITLE
IRC Notification bot

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#102]
The Notifico! service provides easy hooks for GitHub, Travis, and other services.

http://n.tkte.ch/ 

The bot "Not-4e01" in #flexget on freenode is a good example of this.

**Comment by BastienLQ** [comment]
In fact, I was wondering if IRC is a good choice : no Tor connection (on Freenode), no log (I don't have any news from BotBot.me), no multi connection from one account. With ~15 guys on the channel, it's not too late to switch to something else.
If we choose XMPP (and I think it's the best choice), GitHub provides an XMPP bot. I can also adapt the [Nuolez.io bot](https://github.com/Nuolezio/nuoleziobot).

**Comment by pR0Ps** [comment]
My vote would be to keep using it.

I don't think blocking people using Tor is really a problem, in fact, it probably cuts down on spamming. To connect from multiple places at once, just register a different nick per device, and alias them to your account (for example, I have `pR0Ps` and `pR0Ps_` under my account).

Regarding logs, the [Freenode channel guidelines](https://freenode.net/channel_guidelines.shtml) recommend against publicly logging everything anyway. Using a bouncer of some kind that's always connected can feed you the chats you missed when you reconnect (this is what I use).

I'm pretty biased for IRC since I was a pretty heavy user of it before this project, but there's a reason tons of OSS projects use it. It's got critical mass dev-wise, webchat makes it easy for the average user to drop in, and there are lots of clients and related tools for it.

**Comment by johanw666** [comment]
"I don't think blocking Tor users is much of a problem"

Do you? I run an exit node at home and my IP address gets blocked, wether I come from the Tor network or not.

**Comment by BoBeR182** [comment]
Anonymous development is the only true way to create good security apps.

**Comment by pR0Ps** [comment]
@johanw666: I typically don't use Tor or run a run exit node so I didn't realize this before, but Freenode actually has [an entire section on their website](https://freenode.net/irc_servers.shtml#tor) about connecting to Freenode using Tor. Not only is it possible, but: "The freenode network welcomes Tor users."

@BoBeR182: Incorrect. You need people you trust to write/review/deploy the code. Otherwise you'll have to review every line and compile it yourself. If you're doing that every time we push an update, I'd be very surprised (and impressed at your dedication).

**Comment by BoBeR182** [comment]
By anonymous I should have specified pseudonym are the way to go as trust and merit can be assigned but legal identities do not need to be known. 

As for freenode if you join #freenode the topic clearly states that TOR support is down at the moment.

**Comment by BastienLQ** [comment]
Yes, Tor is currently blocked on Freenode, I suppose to avoid spam/flood (like a lot of Internet services).

I don't wan't to run a bouncer to get logs. This would be a core functionality; I understand IRC is designed to be simple, but that is why it is not for us. We need at least logs and mobility: XMPP allows to use a single account from different points. I'm not all the time in front of my l

**Comment by BastienLQ** [comment]
Yes, Tor is currently blocked on Freenode, I suppose to avoid spam/flood (like a lot of Internet services).

I don't wan't to run a bouncer to get logs. This would be a core functionality; I understand IRC is designed to be simple, but that is why it is not for us. We need at least logs and mobility: XMPP allows to use a single account from different points. I'm not all the time in front of my laptop but I want to be still able to answer to people.

**Comment by BastienLQ** [comment]
I think we should take a look at [Rocket Chat](https://github.com/RocketChat/Rocket.Chat): it's a Slack like online chat and there's a [WIP IRC gateway](https://github.com/RocketChat/Rocket.Chat/issues/216). It will allow us to log chatrooms and to keep IRC compatibility (for dinosaurs like you, @pR0Ps :-P). And [XPPP support is planned](https://github.com/RocketChat/Rocket.Chat/issues/404).

I will  move the SMSSecure website from France to Switzerland or Luxembourg in the next days, and I can in the same time install Rocket Chat. Then, using [Hubot](https://github.com/github/hubot) (Rocket Chat supports Hubot) we could develop a home-made bot.

**Comment by pR0Ps** [comment]
Closing due to age and inactivity
