### ISSUE TITLE
Feature: choose the delay (repeat alerts)

### ISSUE THREAD

**Issue by maxauvy** [SMSSecure/SMSSecure#104]
Hi there,

I just configured my SMSSecure app to repeat alerts (once) on incoming SMS. That's nice, but is it possible to make the delay between 2 notifications customizable? Something like 15s, 30s, 1min...

What do you guys think of that?

**Comment by pR0Ps** [comment]
We opted to go with what TextSecure recommended and switch the interval to 2 minutes instead of 10 seconds (behaves like iMessage now).
