### ISSUE TITLE
Swedish translation is partially in English, even though TextSecure has it all in Swedish

### ISSUE THREAD

**Issue by Thunderpig72** [SMSSecure/SMSSecure#108]
Hello. The Swedish translation of SMSSecure has certain parts written in English. This is very obvious on the settings screen, and I'll be posting a picture of that as soon as I get home.

This results in strange sentences like
Incoming på
Passphrase av, Screen security av

In a chat with a non-SMSSecure user, it says "Invite" in English as well.

The interesting thing is that when I open TextSecure, it's all in Swedish.

**Comment by pR0Ps** [comment]
All of our translations are managed by Transifex. Currently the Sweedish translation is at 93% complete.

If you have the time, you can provide the translations on Transifex here: https://www.transifex.com/projects/p/smssecure/viewstrings/#sv/strings/42062781?translated=no
