### ISSUE TITLE
Dual SIM device support

### ISSUE THREAD

**Issue by masterkorp** [SMSSecure/SMSSecure#109]
Hello,

I have a [Samsumg Galaxy Grand Neo Duo S](http://www.gsmarena.com/samsung_galaxy_grand_i9082-5163.php) which is a dual sim device.

I would like to choose which SIM I send the SMS from like I would normally. Currently SMSSecure it just sends from my first SIM.

It seems that on the version of my Android version (4.2.2) the [dual sim implementation is made by the manufacturer itself](http://stackoverflow.com/questions/14517338/android-check-whether-the-phone-is-dual-sim/17499889#17499889) but its not entirely impossible do figure out.

What do you think of this ?

**Comment by Dostoi** [comment]
See #86

**Comment by pR0Ps** [comment]
Closing as duplicate
