### ISSUE TITLE
Secure MMS doesn't work, unsecure MMS does

### ISSUE THREAD

**Issue by justbittin** [SMSSecure/SMSSecure#112]
I worked to get secure MMS to work between Boost Mobile and T-Mobile phones - it always comes back as a bunch of garbled characters, with the 'lock' missing from the transfer.

If we select 'insecure' and send the pics, everything is good.

This was one of my reasons for switching to SMSecure from Textsecure, as I wanted end to end MMS encryption.

Please help.

**Comment by justbittin** [comment]
Further information.  I have tested small to large .jpg pictures.  None will send through 'secure mms' - click over to insecure, all go through and work.

So this isn't a connectivity issue, we are both connecting to our MMS servers properly.

Any secure MMS comes back as ALOT of garbled characters.  The 'lock' icon is not at the bottom of the message.

**Comment by BastienLQ** [comment]
I need more information about your environment. Can you attach or send to support@smssecure.org a log?

I failed to reproduce your bug, but I suspect that one of your mobile provider wants to compress images.

**Comment by justbittin** [comment]
Device  : samsung SPH-M830 (prevail2spr)
Android : 4.1.2 (M830VPBMD5, JZO54K.M830VPBMD5)
Memory  : 12M (0.18% used, 48M max)
Memclass: 48
OS Host : SEP-131
App     : SMSSecure 0.6.0

--------- beginning of /dev/log/main
D/dalvikvm( 3702): WAIT_FOR_CONCURRENT_GC blocked 0ms
D/dalvikvm( 3702): GC_EXPLICIT freed 2K, 25% free 9900K/13059K, paused 3ms+17ms, total 170ms
W/PassphraseRequiredActionBarActivity( 3702): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 3702): initializeClearKeyReceiver()
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
I/Choreographer( 3702): Skipped 47 frames!  The application may be doing too much work on its main thread.
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
W/PassphraseRequiredActionBarActivity( 3702): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 3702): initializeClearKeyReceiver()
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
D/SensorManager( 3702): registerListener :: handle = 1  name= Acceleration Sensor delay= 200000

**Comment by justbittin** [comment]
is that what you needed?  If compression is a factor, is there a work around?

Again, i have tried every size image, even a 5 x 5 px png, won't send secure.  All images send fine insecure.

**Comment by justbittin** [comment]
Here is another:

Device  : samsung SPH-M830 (prevail2spr)
Android : 4.1.2 (M830VPBMD5, JZO54K.M830VPBMD5)
Memory  : 12M (0.10% used, 48M max)
Memclass: 48
OS Host : SEP-131
App     : SMSSecure 0.6.0

--------- beginning of /dev/log/main
D/dalvikvm( 3702): WAIT_FOR_CONCURRENT_GC blocked 0ms
D/dalvikvm( 3702): GC_EXPLICIT freed 204K, 21% free 10389K/13059K, paused 15ms+5ms, total 194ms
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
W/PassphraseRequiredActionBarActivity( 3702): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 3702): initializeClearKeyReceiver()
W/MmsSmsDatabase( 3702): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 1) ORDER BY date_received ASC)
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
W/TelephonyUtil( 3702): Choosing MCC+MNC info from TelephonyManager.getSimOperator()
W/ApnDatabase( 3702): Querying table for MCC+MNC 311870 without APN name
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
D/SensorManager( 3702): registerListener :: handle = 1  name= Acceleration Sensor delay= 200000  
W/ApnDatabase( 3702): Returning preferred APN Apn{ mmsc: "http://mm.myboostmobile.com", proxy: "68.28.31.7", port: 80, user: "none", pass: "none" }
W/MmsSmsDatabase( 3702): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/IncomingBubbleContainer( 3702): onCreateView()
W/IncomingBubbleContainer( 3702): onCreateView()
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
D/SensorManager( 3702): unregisterListener::  
I/SensorManager( 3702): Set normal delay = true
W/InputEventReceiver( 3702): Attempted to finish an input event but the input event receiver has already been disposed.
D/SensorManager( 3702): registerListener :: handle = 1  name= Acceleration Sensor delay= 200000  
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
D/SensorManager( 3702): unregisterListener::  
I/SensorManager( 3702): Set normal delay = true
W/MmsSmsDatabase( 3702): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 1) ORDER BY date_received DESC) LIMIT 1
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
W/PassphraseRequiredActionBarActivity( 3702): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 3702): initializeClearKeyReceiver()
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3702): Incrementing activity count...
W/KeyCachingService( 3702): onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3702): Decrementing activity count...
I/Adreno200-EGLSUB( 3702): <ConfigWindowMatch:2089>: Format RGBA_8888.
D/SensorManager( 3702): registerListener :: handle = 1  name= Acceleration Sensor delay= 200000

**Comment by BastienLQ** [comment]
I'm confused in your logs. Can you clarify which one is from the sender and which one is from the receiver? Additionally, could you compare picture's size between your phones?

**Comment by pR0Ps** [comment]
Got a report of this happening in v0.11.0

Both clients are on Sprint MVNO's (Virgin Mobile and Boost) and have the same issue no matter which person sends the secure MMS. Unsecured MMS's go through as normal.

**Comment by BastienLQ** [comment]
Closing in favor of #296.
