### ISSUE TITLE
Unread Badge Support

### ISSUE THREAD

**Issue by justbittin** [SMSSecure/SMSSecure#113]
This is almost a must for SMS clients these days.

Here is an opensource project that would easily bring this to SMSSecure without problem, and supports multiple devices/launchers.

https://github.com/leolin310148/ShortcutBadger/

**Comment by pR0Ps** [comment]
See #36.

We had problems with it throwing exceptions constantly and since it only works on a handful of Launchers (not even stock launchers KitKat+) we removed it.

I'll take a look and see if it's improved since then but I'm not optimistic.

**Comment by justbittin** [comment]
The author is constantly updating, it is not abandoned.  Also, as you noted, Textsecure works with Unread badges.

It is more than just a few.  It works on many launchers from the readme file.

If textsecure patched it, why not pull from them, they are infact, opensource - and as a fork...  

I think it is a quick way to see unread count.  I would disagree that it never tooj off, more and more apps now offer it.

**Comment by justbittin** [comment]
**took

**Comment by BastienLQ** [comment]
In *master*, you can have the number of unread messages. Just wait SMSSecure 0.7 or build it yourself. ;-)
![count](https://cloud.githubusercontent.com/assets/7220484/7403696/b535e3e2-eed8-11e4-8302-75fee1c75d4e.png)
