### ISSUE TITLE
Pull request for encrypted backup

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#115]
I know I'm misusing the Git issue system a bit for this.

I have put back in the code for encrypted backups. As far as I have tested it it works. I now wanted to create a pull request with those changes that affect 3 files (ExportFragment.java, export_fragment.xml and strings.xml) but Android Studio keeps telling me I'm pulling an empty changeset.

Before putting much time in trying to figure this out, would the developers consider importing this change or would it be rejected because the TextSecure authors reported problems (I never saw them specified though) with this code?

**Comment by BastienLQ** [comment]
Sure we will accept the PR, but after a lot of tests. ;-)
You can also mail us your patch.

**Comment by johanw666** [comment]
OK, I mailed the files to it to support@smssecure.org.
