### ISSUE TITLE
Adding an option to display to which number a received SMS was sent (for multiple SIM devices)

### ISSUE THREAD

**Issue by sevan6** [SMSSecure/SMSSecure#122]
Hi,

Using a Fairphone (Android 4.2.2) I have two SIM in my device.
When receiving messages in SMSSecure, I cannot tell which SIM received it, as SMSSecure does not support multiple SIM yet.

A workaround would be to display the 'sent to' number in the *Message* *Details* screen.
This could be an option, disabled by default as monoSIM devices are the standard. Multiple SIM device users could activate the feature and see in the message details which SIM received the message.

Thanks and keep up the great job,
Sevan

**Comment by der-stefan** [comment]
SMSSecure gets confused when sending a SMS to a person with dual SIM. In my address book he is one contact with two numbers. I guess, every SIM has an own key.

**Comment by pR0Ps** [comment]
I looked into this a bit. The incoming message doesn't actually have a recipient number in it. See the SMS_DELIVER column in [this table](https://en.wikipedia.org/wiki/GSM_03.40#TPDU_Fields) for what we have access to.

Additionally, even with the new [multi-SIM APIs in 5.1](https://developer.android.com/about/versions/android-5.1.html#multisim), it doesn't seem possible to determine which SIM received the message, only which subscription(s) are active at the time when the message was received.

Feel free to reopen this if a reliable way of getting the recipient address of an incoming SMS is discovered.
