### ISSUE TITLE
can't import Backup from smssecure in Textsecure

### ISSUE THREAD

**Issue by amazing-clemo** [SMSSecure/SMSSecure#123]
Tried to switch back to textsecure and wasn't able to import the backup from smssecure (it works the other way round). I only.could import an old backup created by textsecure. (Please ask if I want backup as textsecure or as smssecure)

**Comment by BastienLQ** [comment]
For now, we only need a log.

**Comment by pR0Ps** [comment]
We're not making an effort to aid in migration back and forth between apps (and are not going to put an option in to do that), but I think you'll find that if you export a plaintext backup and rename it so it's the same as TextSecure's plaintext backup, it should work.

**Comment by amazing-clemo** [comment]
Thank you, it solved my problem. But I don't think it's confusing, because I'd expected it to export it in the same way as textsecure because it imported it without problems (which was really great!). Maybe a prompt will confuse some people, so is it possible to add a option in the settings menu?

**Comment by pR0Ps** [comment]
We'll accept TextSecure's backups as valid backup sources (if no SMSSecure backup is found), but exporting to TextSecure would overwrite existing TextSecure-exported backups, something which would be unexpected and could cause data loss.

In other words: ["Be conservative in what you do, be liberal in what you accept from others"](http://en.wikipedia.org/wiki/Robustness_principle).
