### ISSUE TITLE
Self compiled version does not show build ID

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#124]
This may be more of a question than a real issue, but before 0.6.0 a self-compiled version with some changes in the sources gave in settings - About SMSSecure the build ID from the last commit that I downloaded. Since 0.6.0, it shows my changed version number but the build ID field is gone. Is this a glitch in the build scripts or expected behaviour?

**Comment by BastienLQ** [comment]
The build ID is not displayed if Git is not available (in `PATH`).
