### ISSUE TITLE
Add an "automatic mobile data" and colours customization

### ISSUE THREAD

**Issue by ToNIX-** [SMSSecure/SMSSecure#127]
Any chance for an option to automatically turn on the "mobile data" when sending/receiving MMS?

Also, add options to customize bubble colors (sent, received and custom colors per contact)?

Thank you!

**Comment by pR0Ps** [comment]
Automatically turning mobile data on and off isn't something we're going to add (people typically don't like apps messing with that stuff). Custom themes and colors will be done by #65.
