### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by BastienLQ** [SMSSecure/SMSSecure#13]
In 4e039c722a0c9dcb2ed011a870665291c277ec92, I added strings that must be translated. We should use Transifex for this.

**Comment by SecUpwN** [comment]
@BastienLQ, out of pure interest: Why Transifex? We're also working on an App, the [Android IMSI-Catcher Detector](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) and are aiming to localize it as well. Hence I am interested in your choice of Transifex over others. Why not [Crowdin](https://crowdin.com/page/android-localization), [Weblate](http://weblate.org/), [OneSky](http://www.oneskyapp.com/) or anything else?

**Comment by BastienLQ** [comment]
@SecUpwN With Transifex, TextSecure's contributors might join us; as it is on the same platform, they will not lose their bearings.

**Comment by pR0Ps** [comment]
Transifex is set up and the strings are in it: https://www.transifex.com/projects/p/smssecure/ . I'll add that URL to the readme and close.
