### ISSUE TITLE
MMS not working- need to be able to set MCC/MNC. 

### ISSUE THREAD

**Issue by DiogenesT** [SMSSecure/SMSSecure#131]
This is also present in TextSecure, encrypted MMS or not. 
Carrier Republic Wireless needs a custom MCC & MNC for working (regular) MMS on third party apps.
From https://community.republicwireless.com/docs/DOC-1948?forceNoRedirect=true#jive_content_id_Send_an_MMS_using_Hangouts

Name: Enter your desired name.
MMSC: Should be set to http://localhost
MMS proxy: Should be set to 127.0.0.1
MMS port: Should be set to 18181
MCC: Should be set to 310
MNC: Should be set to 000

**Comment by DiogenesT** [comment]
Opened same issue for TextSecure: https://github.com/WhisperSystems/TextSecure/issues/3156

**Comment by pR0Ps** [comment]
Closing based on the outcome of the upstream discussion.
