### ISSUE TITLE
Deactivate the 1 letter logo per conversation

### ISSUE THREAD

**Issue by KaitoKito** [SMSSecure/SMSSecure#133]
Hi,

Since 0.8.0 update each conversation I have got a logo with a big letter, which is the first one of the name of the friend I'm discussing with. It also appears on the notification bar when I receive a message.

I didn't found how to deactivate this, if it's doable but I didn't found it excuse my message. But if it isn't, can the devs add an option do deactivate this ? It's really annoying, especially on the notification bar.

Thank you very much anyway for working on this app.

**Comment by pR0Ps** [comment]
This is intentional and is part of the shift towards a more "material"-looking app.

To be clear, this only happens when the contact has no picture set. It replaces the grey generic person image.
