### ISSUE TITLE
Bugs with discussion group

### ISSUE THREAD

**Issue by quentinhardy** [SMSSecure/SMSSecure#134]
Hello,

First, I would like to say it's really good to have this application. Really: good job :) 
I have no one problem with this application when I don't use a discussion group.

I'm using smssecure 0.8.1 (last version in the app store).

However, I have not found a trick to **enable the encryption of sms in a group**. Is it possible?

Moreover, when you receive the first sms from a new discussion group created, a new discussion group **is created** in the list of discussions (bug1). Consequently, the Initial group contains my first sms only. Other sms are stored in the new discussion group created by the application.

To finish, when I send a sms through a discussion group, I *receive my own sms in this discussion group*. The application shows my sms with my phone number (bug2).

Thank you a lot for you work (past and futur :)).

**Comment by Thunderpig72** [comment]
I was just wondering whether or not group SMS encryption is available. So, is it? Anyone knows for sure?

**Comment by BastienLQ** [comment]
There aren't. I'm working on this feature as part of #209.
