### ISSUE TITLE
Phone reboot when locking the screen

### ISSUE THREAD

**Issue by bl00m** [SMSSecure/SMSSecure#136]
Hi,
Whenever I lock the screen with SMSSecure open in front, I can't unlock and when I try : the phone reboot. It happened every times. I have to push the app to the backward for locking without trouble.

Device info: Wiko Birdy 4G , stock android 4.4.2, SMSSecure 0.8.1

Debug Logs : https://gist.github.com/e493d0a0b42f0c4c95a1

**Comment by pR0Ps** [comment]
Could you grab a full logcat from the device (not just the app)? The log provided doesn't show anything going wrong. As the crash seems to be in the OS, the system log would have more information.

How to get the system log: http://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat

**Comment by DeLadoss** [comment]
Yes I always had the same behaviour with TextSecure with my Birdy 4G.

You have to disable the snapshot screen protection in the option of the App and it won't crash anymore. You have less protection but the App is useable at least.

**Comment by bl00m** [comment]
The phone drop in water, end of the story.
Thanks ;)
