### ISSUE TITLE
API

### ISSUE THREAD

**Issue by DJaeger** [SMSSecure/SMSSecure#144]
Please add an API to access the sms data like the stock app allows, but which requires an approval of the accessing app.

With that it would be possible to use this app with other apps, that access the sms database.

For example to sync messages (e.g. [ownCloud-SMS](https://github.com/nerzhul/ownCloud-SMS-App)) or to show if and how much unread messages are avalable (e.g. in [DashClock Widget](https://github.com/romannurik/dashclock)).

I think something like the approval by [OpenKeychain](https://github.com/open-keychain/open-keychain).

**Comment by c33s** [comment]
:+1: 
also it would allow controlling the phone by apps like [condi][1] or [tasker][2] (for unmuteing the phone,...)

[1]: https://play.google.com/store/apps/details?id=il.co.kix.minitasker
[2]: https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

alternatively would it be great to have a checkbox to "push" unencrypted sms to the stock sms app

**Comment by DJaeger** [comment]
If you push your unencrypted messages to stock app they would be readable by all apps with permission to read sms and same code than using stock app.
But you can't control yourself, which apps have access.
While using a own API you have more control on what apps can do and what not.
The apps that want to read the messages have to include the API which needs more work, put prevents malicios messages spying apps to read this "secure" messages.

**Comment by c33s** [comment]
don't get me wrong, an api is a cool thing, therefor i add the :+1: 

your security concern is legitimate but if you have the option to only forward plain / unencrypted (not decrypted) messages, i don't think it is a security issue.

the advantage of this option is, that you don't have to ask app author xyz to add support for the api, it simply works out of the box. this means sms backup apps work, owncloud sms backup works,... just out of the box.

even more secure would be to not create an extra api where previous crypted sms are transfered unencrypted to some owncloud server, if i forward them crypted, they are still save on the owncloud server.
i would be interested in native apps (linux, windows, mac) which are able to decrypt messages i have backuped (of course some kind of key export function should be provided in smssecure).

i am not sure if making it more work for developer to access the sms database is the right thing to provide more security. if i allow an app access to the sms database i am ok with it, and want that the app is able to access it.
if you really want to prevent apps to read your data, maybe [xprivacy][1] is the way to go 

[1]: http://repo.xposed.info/module/biz.bokhorst.xprivacy

**Comment by DJaeger** [comment]
If I just forward them crypted they are also safe on the ownCloud server, thats right, but you can't use the adventage of reading them on the web and I'm not sure if they could be decrypted later by SMSSecure or any other application.

Also this prevents from having a twoway sync.

If the ownCloud App, to remain on the same example, introduce an feature to write messages from website, if crypted or not, they can't be visible within the app.

You could think of using both, the own API and the simple forward, to support simple features with existing calls to sms database and allow willing apps to use more adventaged features.

**Comment by DJaeger** [comment]
Yes you are right, you can prevent unwanted apps from accessing your sms database by using xprivacy, but I think most people don't know which apps can read sms and also don't know xprivacy.

So the safest way is the best way and that would be to only allow apps that explicitly have been approved by the user (opt-in not opt-out).

**Comment by pR0Ps** [comment]
The stock SMS app doesn't provide an API of any kind. IIRC, the way that apps see the number of unread messages is by running queries on the system SMS database. You already have a "whitelist" of approved apps that can do this: Apps that have the READ_SMS permission and apps that you give root access to.

Since SMSSecure uses it's own database to store the messages, it doesn't work with those applications. Something like #145 would be a better way of integrating SMSSecure messages with other applications since they expect SMS messages to be in the system SMS database.

**Comment by DJaeger** [comment]
That's all what we said already.
But I speak of features, you can't to with the system SMS database.
So why not including it?

**Comment by pR0Ps** [comment]
A specific SMSSecure API would take a lot of effort to design, develop, test, and maintain. Other apps are extremely unlikely to actually do anything with it. It's not worth the development time that could be spent on things more users would benifit from.

**Comment by Salamandar** [comment]
Hi !
I'm just someone who doesn't have the time right now to do anything :°

But this API idea would be great. It would allow SMSSecure to be more
"ecosystem-friendly" with custom launchers, widgets, things like
AirDroid and more…
Right now those apps can't access AT ALL the messagesSecure.

It doesn't need to be something really "complex". Just some
SendMessage(), GetMessageList(Contact contact), GetUnreadCount() would
be great for a start.

And it would allow to easily create a library included and used by the
stock app (like Whisperpush in CyanogenMod).

Well, I can't say it's very important right now. There are some bugs to
be resolved before that ;)


Le 03/06/2015 17:57, Carey Metcalfe a écrit :
> A specific SMSSecure API would take a lot of effort to design, develop,
> test, and maintain. Other apps are extremely unlikely to actually do
> anything with it. It's not worth the development time that could be
> spent on things more users would benifit from.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SMSSecure/SMSSecure/issues/144#issuecomment-108496755>.
> 

-- 
Félix Piédallu
Président du Club Robotronik Phelma
06 51 41 32 48
Manjaro Linux. Feel the freedom.

**Comment by DJaeger** [comment]
I don't want it done in next days, but it would be great to have at any time later.
And I think the app will get more contributers at time and some of them will think this idea is really great and will help developing this.
If I find some free time I would also try to start with it.
It would be great, if you let this open for later.

**Comment by Salamandar** [comment]
@DJaeger , completely agree :) And if I have some time, i'll try to start something like it.

**Comment by pR0Ps** [comment]
The way to be "ecosystem-friendly" is not to create a custom API that apps have to specifically be coded to use, it's to conform to the existing conventions other apps already use.

Examples of this would be the sending of messages via intents (in the app now) and forwarding messages to the system SMS database where other apps expect them to be (see #145).

A custom API would add a lot of cruft to the project and go mostly unused and therefore won't be implemented.
