### ISSUE TITLE
Auto detection

### ISSUE THREAD

**Issue by der-stefan** [SMSSecure/SMSSecure#147]
It would be a great feature, if there would be some kind of auto detection, if the other side uses SMSSecure.
One solution would be to send a handful of special characters in the end of a SMS (if the user enabled it in the settings and if this doesn't lead to a multi-SMS). The other side then gets to know about the possibility of using SMSSecure and could start a key exchange.

**Comment by pR0Ps** [comment]
This is exactly what already happens.

**Comment by der-stefan** [comment]
Damn! You are awsome!
