### ISSUE TITLE
AOSP keyboard ?

### ISSUE THREAD

**Issue by NicolasKAROLAK** [SMSSecure/SMSSecure#148]
Hello,

Why don't use the AOSP keyboard in the app ?

Anyway, the use of smileys is not very convenient with the SMSSecure keyboard, the switching is a little painful.

**Comment by pR0Ps** [comment]
Not sure what you mean. We don't control the keyboard, your system does.

**Comment by NicolasKAROLAK** [comment]
Yes my bad, I double checked and that the same keyboard... Except for the emojis.
