### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#15]
[Moxie](https://github.com/moxie0) of the parent project has requested that we change the name to avoid user confusion. As a group, we have settled on SMSSecure.

TODO:
 - [x] IRC Channel (#SMSSecure on Freenode)
 - [x] Github Organization/Repo (including support email - renaming both without losing data is possible)
 - [ ] App identifier (change to org.smssecure.smssecure - no caps is customary)
 - [ ] In app strings
 - [ ] README
 - [x] Website domain
 - [ ] [LinuxFR article](http://linuxfr.org/news/securedtext-les-sms-et-mms-chiffres-sur-android-ce-n-est-pas-fini)

**Comment by johanw666** [comment]
This means delaying the F-Droid application as well I presume.

**Comment by BastienLQ** [comment]
@johanw666 I will open a new MR in ~1h

**Comment by BastienLQ** [comment]
@pR0Ps I changed to org.SMSSecure.SMSSecure. Should I reset the commit?

**Comment by BastienLQ** [comment]
Well, I force pushed...

**Comment by vn971** [comment]
Hi, is there a ticket that explains the move from "SMSSecure" name to "Silence" ?

I'm not sure, but it might be confusing for new users.

Certainly was for my wife: I've installed F-Droid and Silence (along with other apps) on your phone but didn't have the time to explain everything about Silence. So she just had the phone. It was relatively hard for her to figure out what app should be use to send SMS-es (actually, she didn't figure it out at all until she got an incoming SMS).
Again, this is obviously not statistically representative, so I'd just like to know the reasoning on the last rename.

**Comment by johanw666** [comment]
@vn971 see https://github.com/SilenceIM/Silence/pull/383

**Comment by vn971** [comment]
@johanw666 I see. Thanks. It's very surprising to see how a company could take the words "SMS" and "Secure", merge them and get a trademark license. It's also a surprise that nobody has taken the whole non-reserved English dictionary and trademark everything inside, to take the idea to absurd. Anyway, this is off-topic. Thanks again.
