### ISSUE TITLE
"Archive" just like Messenger (SMS, not facebook)

### ISSUE THREAD

**Issue by Salamandar** [SMSSecure/SMSSecure#150]
Hi !
In Messenger we can archive a conversation by sliding it to the right or left (in the conversation list activity). It would be great to have this "archiving" in Messenger too !
(Maybe the sliding too, if it's not too much work.)

**Comment by pR0Ps** [comment]
Just curious: What benefit does archiving a conversation have? Is it just for "neatness" or is there some utility to it?

**Comment by Salamandar** [comment]
Yep : to not see it in the general conversation list, but still having access to it (for me it's the messages from my operator, or my bank). It would also be to have a "trash bin", and being able to restore conversations from it.

**Comment by BastienLQ** [comment]
A search functionality would be more useful, I think.

**Comment by donutz** [comment]
I'd like Archive functionality too. 

That way when I'm done with a conversation, I can keep a record of it without it taking up space in my message "inbox". It's rarer that I need to refer back to older message contents, so search would be a less important feature for me.

**Comment by pR0Ps** [comment]
Implemented in 886258bc2a7
