### ISSUE TITLE
MMS doesn't support animated GIFs

### ISSUE THREAD

**Issue by remileduc** [SMSSecure/SMSSecure#153]
SMSSecure is a great app and I love it! It only lacks few things to be absolutely awesome :)
First thing is the possibility to exchange animated GIFs via MMS.

If I send this picture to a friend (see attached file) he should be able to see it, with the animation.
![le_film_alien2](https://cloud.githubusercontent.com/assets/2204024/8062621/fa981578-0ed0-11e5-9d29-0f2e8365fa96.gif)

what happens actually is: the application take only the first image of the GIF and send it in a very tiny dimensions.
finally, SMSSecure should be able to display the animated GIF, which is probably not the case actually (when I add the picture, there is no way to launch the animation)

As far as I know, It shoul be possible to send a GIF via mms if the GIF weights less than 300 kio. What my previous sms app does (messenger, the default from cyanogenmod) is:
- if the GIF is less than 300 kio, send it as it
- if the GIF is more than 300 kio, take only the first image
  - if the first image is less than 300 kio, send it
  - if the first image is more than 300 kio, compress it as if it was a normal JPEG file

I hope this feature will be added soon :)
thanks for your app!

**Comment by johanw666** [comment]
Maybe related to  WhisperSystems#3381

**Comment by remileduc** [comment]
You're right, that seems to be very related. Sorry I missed it when I've searched for this bug :/
As it is a problem of library, does it mean we won't see GIF support any soon?

**Comment by johanw666** [comment]
I don't know, since SMSSecure tries to follow TextSecure with these kind of things it might be that we'll have to wait till TextSecure solves this. But the devs should answer that one.

**Comment by BastienLQ** [comment]
SMSSecure supports GIFs in `master`.

**Comment by remileduc** [comment]
Sorry for the late, I wanted to thank you for your reactivity and your implication.
please continue like that :)
