### ISSUE TITLE
Crash while trying to send MMS

### ISSUE THREAD

**Issue by Arlakt** [SMSSecure/SMSSecure#158]
Hi,
I used the "share" button on a picture in Google Photos to send a MMS. The App asked me my password, and when I touched the arrow it just crashed. Two tests, same thing.

Phone : Wiko Kite
Android : 4.4.2
Debug log : https://gist.github.com/c60020c6547fa15efcb5

**Comment by johanw666** [comment]
Maybe solved in https://github.com/WhisperSystems/TextSecure/commit/cb3cf7789ff8d5b90ca69c73764b92c82e41b9d9 ?

**Comment by Arlakt** [comment]
Indeed it seems that is the fix for this !
