### ISSUE TITLE
Implement retransmissions?

### ISSUE THREAD

**Issue by d33tah** [SMSSecure/SMSSecure#159]
Recently I was getting reports of SMSes failing to decrypt with an error message. Sending them again fixed the problem and I am getting the impression that parts of them are lost in transit. How difficult would it be to implement retransmissions in SMSSecure so that in case of an error, a message "please resend" is sent and the other party automatically resends a message then? I know that there is the risk of wasting a lot of money this way, but if properly implemented, it could be useful in my case.

I might be willing to put a bounty of the task - please let me know how much would be appropriate here.

**Comment by pR0Ps** [comment]
Something like this would add a bunch of complexity to the protocol as well as allow for the possibility for the app going crazy and repeatedly firing off "please resend" messages, costing $$$ to the sender, as well as the person on the other end (who is presumably responding back with the message over and over).
