### ISSUE TITLE
SMSSecure send cyphered SMS to standard SMS application

### ISSUE THREAD

**Issue by Informartiste** [SMSSecure/SMSSecure#160]
Hello,
My SMSsecure (v.0.9.0 on Android 5.0.1) exchanged keys and then sent cyphered SMS to one of my contact (Nokia Lumia with Windows Phone). But my contact was not able to decypher the SMS. He received incomprehensible data. I do understand the reason why the data were incomprehensible for my contact, but he shouldn't have received cyphered SMS.

I had to close the cyphered session to be able to send readable SMS again with this contact.

**Comment by johanw666** [comment]
SMSSecure does not run on windows phone so it's normal he could not decrypt the sms. However, I'm surprised you could have exchange keys. Did the other person exchange keys with an other phone running Android?

**Comment by Informartiste** [comment]
As I said. I do understand the windows phone can't decrypt my SMS. The question is: "Why does my phone send cyphered SMS?"

I think the other person didn't exchanged key with another SMSSecure on Android, other than me.

**Comment by johanw666** [comment]
Could be a bug in SMSSecure thinking incorrectly you did exchange keys. However, if you long-press on the send arrow you get the options send secure or send insecure sms.

**Comment by Informartiste** [comment]
I dont know why but they exchanged keys.
And as soon as the keys were exchanged, the other person received cyphered and incomprehensible SMS from me.

![smssecure](https://cloud.githubusercontent.com/assets/12525200/8156270/c8bd4864-134b-11e5-8e1a-d2ae0b99ef2c.png)

**Comment by pR0Ps** [comment]
This is working as designed. You were sent a valid key (somehow, not sure), you replied back with a key, and started sending encrypted messages.

Not really sure what can be fixed here. Just end the session via the lock icon in the top bar and send messages normally.
