### ISSUE TITLE
[SMS and MMS outgoing] point (with additional options) possible?

### ISSUE THREAD

**Issue by revuwa** [SMSSecure/SMSSecure#163]
I came across this issue: http://redmine.replicant.us/boards/9/topics/9639 and so I kindly wanted to ask if it would be possible to add some settings point like "SMS and MMS outgoing" to control some automatically sent background stuff, like in this example: suppress the delivery report acknowledgement from the target device?

I can't say much more about the reasons, why the thread-holder wants to do so. The question is just if such a implementation would be possible over your great app - or is this settled a in a deeper (e. g. protocol) layer, without any chance to modify / switch this kind of settings over apps?

Thanks in advance for any help and or response.

**Comment by johanw666** [comment]
Delivery reports are sent by the network uppon delivering the message at the recipients phone. There is nothing SMSSecure can do to influence them being sent.

**Comment by revuwa** [comment]
Thanks for the clarification.
