### ISSUE TITLE
Remove expiration

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#165]
The current build expires 180 days after build time. I'm doubtfull if we should keep such a forced upgrade mechanism in the builds. The quickest way to remove it would be to set in util/Util.java the function isBuildFresh to true:

```java
  public static boolean isBuildFresh() {
   // return BuildConfig.BUILD_TIMESTAMP + TimeUnit.DAYS.toMillis(180) > System.currentTimeMillis();
  return true;
  }
```

**Comment by Thunderpig72** [comment]
The only problem I'm seeing with removing is in case new features are introduced that require both users to have the latest update, or if a new, stronger type of encryption is added. There will always be people who never ever update their apps unless they are forced to. Let's say that 2 months from now SMSSecure introduces encrypted group chats. Most people will update, and then we have that last 5% that just doesn't give a crap about updating.

Last time I checked TextSecure set their expire date to 90 days, for that exact reason. I guess SMSSecure being an SMS-app makes forced updates quite meaningless though.

**Comment by johanw666** [comment]
If the encrypted message format would change so that older clients could not decrypt it anymore, something could be made that a warning would be given.

But please not a repetition of the events of TextSecure 2.7.0, which removed important functionality without warning (for most people who don't read the Whispersystems blog) combined with a forced upgrade path. I would still prefer a combined push/sms messenger like 2.6.4 was, and I am able to remove the expiration from the source, but most people are not.

**Comment by BastienLQ** [comment]
I agree, we could disable this annoying feature and replace it by a manual check on the SMSSecure website. SMSSecure needs Internet access to get MMS so we could use this permission to allow users to make a GET request to `https://latest.smssecure.org/` (http if Android is 2.3).
