### ISSUE TITLE
Spam texts: block sender, report spam to provider?

### ISSUE THREAD

**Issue by robertwenner** [SMSSecure/SMSSecure#169]
How do I block a sender or report a spam text, e.g., by forwarding it to T-Mobile as per https://support.t-mobile.com/docs/DOC-2747 ?

**Comment by Thunderpig72** [comment]
Paste the message into a new message to 7726, then send it?

**Comment by johanw666** [comment]
Blocking senders is in the new Textsecure beta and will probably be in SMSSecure once the changes are merged. Reporting spam to a provider is provider specific, I doubt that will be included.

**Comment by robertwenner** [comment]
Is pasting the message good enough or do I need meta information, like email headers?

**Comment by pR0Ps** [comment]
There is a forward option in the overflow menu after you select a message. All it does is start a new message with the same contents (no headers or anything).

Also, within a few weeks there will be a build of SMSSecure being pushed out that includes blocking messages from numbers.
