### ISSUE TITLE
[Feature request] Encrypted backups for SMS database.

### ISSUE THREAD

**Issue by tuxayo** [SMSSecure/SMSSecure#17]

**Comment by BastienLQ** [comment]
Duplicate of #16.

**Comment by tuxayo** [comment]
I thought that encryption keys and SMS database could be separated because currently only the database can be exported.
And maybe there are different challenges for the implementation?

**Comment by BastienLQ** [comment]
It would be easier to export messages and keys, and users will always be able to remove conversations after the import.
