### ISSUE TITLE
Are "notifications of reception" supposed to work ?

### ISSUE THREAD

**Issue by arno-github** [SMSSecure/SMSSecure#170]
My contact switched a few days ago to smssecure, but was used to receive those notifications.
Although I checked the option for her in smssecure, she never received any notification, whereas with the core sms app, she does.
I'll send you versions of OS and apps if you ask...

**Comment by BastienLQ** [comment]
I need a log to help you. ;-)

**Comment by arno-github** [comment]
Former version works fine, thanks :-)
