### ISSUE TITLE
Encryption between SMSSecure and Signal for iOS

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#173]
[![Signal](http://a3.mzstatic.com/us/r30/Purple7/v4/2c/23/60/2c236017-ca69-ea06-2982-13098d9df31e/icon320x320.png)](https://itunes.apple.com/app/id874139669)

Some of my friends happen to be hardcore Apple fan boys. (*sigh*) I hope a secure session is possible.

Since SMSSecure is an awesome fork of TextSecure and TextSecure is compatible with the [Signal Messenger for iOS](https://github.com/WhisperSystems/Signal-iOS), I wonder if SMSSecure is also able initiate an encrypted session to this app. Is it?

* **UPDATE 1:** Just tried to exchange keys and did not get a key back. Guess it does not work (yet)..

**Comment by pR0Ps** [comment]
No. Signal for iOS uses the internet to communicate, not SMS messages like SMSSecure.

If you would like to talk with Signal users, you're going to have to use TextSecure.

**Comment by SecUpwN** [comment]
>If you would like to talk with Signal users, you're going to have to use TextSecure.

Thanks for clarifying, @pR0Ps. Makes perfectly sense since TextSecure only uses Internet as well.
I will refrain from installing anything but SMSSecure. Issue solved. Glad you guys are rocking this!
