### ISSUE TITLE
Sometimes, my sms is not decrypt when I receive it

### ISSUE THREAD

**Issue by adrian3d** [SMSSecure/SMSSecure#174]
Sorry for my english, I'm french. Sometimes, when i receive sms, it is not decrypt. Just I see the sms encrypted in my SMS app by default but SMSsecure don't react. It's crazy.

I'm on Moto G 2014, lollipop (5.0.1).

Thanks !

**Comment by Dostoi** [comment]
Est ce que SMSSecure est marqué comme l'application sms par défaut ?
I'm gonna speak french because it's easier for him but if anyone want to I can speak in english

**Comment by johanw666** [comment]
Google Translate to the help here.
Wether or not it's the default application should not matter. Not on Android >= 4.4, where each app that decalres to handle sms can parse them. If the message is encrypted SMSSecure should handle them on 4.4 and higher, wether it's the defauklt sms application or not.

Is it always from the same sender? Re-initiate a key exchange with that person might solve it.

**Comment by adrian3d** [comment]
No, smssecure is not my sms app by default.

@johanw666 I try this ! Thanks !

**Comment by BastienLQ** [comment]
@Dostoi Please speak English here.
@adrian3d Did you solve your issue? Can you provide a log when the bug occurs?

**Comment by adrian3d** [comment]
@BastienLQ yes, but i don't know how, but it seems works for a week. I can't provide a log. :/

**Comment by papjul** [comment]
Is one of you using SFR network? I'm trying to know if SFR is not randomly adding NULL characters or something which mess up with decrypting. I don't know why they would do that but they already added trackers to Internet pages so why not…
Also this might be related to https://github.com/WhisperSystems/TextSecure/issues/240

**Comment by pR0Ps** [comment]
Seems resolved, reopen if not.
