### ISSUE TITLE
App Crash at first boot or restart

### ISSUE THREAD

**Issue by Kirmaniarslan** [SMSSecure/SMSSecure#175]
SMSSecure app crashes sometime after reboot or at startup of first boot when adding it as system app and the problem is that its incoming SMS activity doesn't starts when boot is completed , enable SMS and MMS receiving activity start running after android device reboot

**Comment by johanw666** [comment]
Why would you install it as system app? AFAIK it has never been tested as such.

**Comment by Kirmaniarslan** [comment]
Even without that if it is installed as normal apk still as its sms receiving services doesn't start after boot   so some time it when u open it it crashes at first and then works fine and i cant find this in ur app  https://github.com/CyanogenMod/android_packages_apps_Mms-caf/blob/cm-12.1/AndroidManifest.xml#L23 which enable the app activity start running after device reboot

**Comment by Kirmaniarslan** [comment]
Here is log https://gist.github.com/anonymous/60002615fdf23677df76

**Comment by johanw666** [comment]
SMSSecure has nothing to do with the Cyanogenmod version of TextSecure that is pointed to in the link above.

**Comment by Kirmaniarslan** [comment]
No i dont mean that , i just want you to start sms receiving services after boot otherwise which cause fc at startup when msg app is set as default .

**Comment by BastienLQ** [comment]
We will publish a new version of SMSSecure in the next days and it could fix your bug. But without a log, I can promise.

**Comment by pR0Ps** [comment]
Can't reproduce in the latest version. @Kirmaniarslan please reopen (with a debug log of the crash) if you still can.
