### ISSUE TITLE
Start secure session first message isn't displayed.

### ISSUE THREAD

**Issue by fustalol** [SMSSecure/SMSSecure#179]
Hey there, I've a very boring bug on SMSsecure (and Textsecure 2.6.4 then) that if I open a new Thread and firstly ask for a secure session, I don't see the message with the key until I tap back and return on the conversation list and re-enter on It. Secondly, the answer with se other user secret key is on a new thread! Why?

**Comment by BastienLQ** [comment]
The first bug is a duplicate of #99.

**Comment by fustalol** [comment]
I don't think It's the same bug, normal message with people without contacts goes pretty well in my case. Only the initial secure message does not work.

**Comment by pR0Ps** [comment]
Confirmed this still exists in v0.13.0
