### ISSUE TITLE
New icon for SMSSecure

### ISSUE THREAD

**Issue by jpfox** [SMSSecure/SMSSecure#18]
If you want, you can use this icon.
![cryptotext-256](https://cloud.githubusercontent.com/assets/5191640/6771962/ef19d53e-d0ef-11e4-8ac2-59d389e29290.png)
I can provide svg format.

**Comment by SecUpwN** [comment]
@jpfox, it's awesome to see that you're going to craft a fresh Icon for SMSSecure, but I actually loved the original round-shaped one. So if you're going to put some work into it, could you possibly ccreate a round one with a unique style? The proposed Icon looks a little too much like Windows 8. Thank you! ;-)

**Comment by BoBeR182** [comment]
Also I feel since we are a different application from TextSecure we might want to adopt a new color, like green?

**Comment by johanw666** [comment]
Green would be appropriate, since TextSecure used that color when it was still an sms application.

**Comment by jpfox** [comment]
Is it better ?
![smssecure-256](https://cloud.githubusercontent.com/assets/5191640/6779272/c64683b2-d15a-11e4-9f2a-81ff14aa50d9.png)

**Comment by jpfox** [comment]
Or purple... looks more serious

![smssecure-purple-256](https://cloud.githubusercontent.com/assets/5191640/6779302/feba5d72-d15a-11e4-98c4-04c3e3e0d342.png)

**Comment by BoBeR182** [comment]
Raise the lock a bit it seems a bit low. Could you recreate the green with hex color #33FF00 and try a purple #9933FF , I really prefer the rounded icon.

Pardon me if it's seemed like nitpicking.

**Comment by jpfox** [comment]
I really like your new purple. Green #33FF00 seems too flashy, so I also propose a darker green (but less than my first proposition) : #00CC00

![smssecure-3](https://cloud.githubusercontent.com/assets/5191640/6780291/172272ce-d164-11e4-9023-daeeec6c9e62.png)

**Comment by BoBeR182** [comment]
Agreed we should have a vote between #00CC00 and #9933FF, unless anyone else wants to try their hand at it, maybe making a dropshadow or outlines. After we get a better consensus we can export as 512px by 512px PNG and replace our current stolen logo.

**Comment by pR0Ps** [comment]
@jpfox: Thanks for providing some mockups for the icon.

Google has published some guidelines on app icons here: http://www.google.com/design/spec/style/icons.html . Since the rest of the app is styled according to material design, the icon should match that.

Also, I like the current design of TextSecure's icon so maybe use that as a starting point, although Moxie (of the TextSecure project) has said that it should be different enough as to not be confused (change color, change shape, although I like the keyhole icon).

**Comment by jpfox** [comment]
Thanks for Google guidelines link... I will try to follow them and propose a new shape.

**Comment by BastienLQ** [comment]
What about that? 
![icon](https://cloud.githubusercontent.com/assets/7220484/6780973/0cb241a6-d16a-11e4-94d2-73e3c9c2fc3a.png)

**Comment by johanw666** [comment]
That's really nice. It both looks enough like TextSecure to indicate some similar functionality and also different enough to avoid confusion.

**Comment by BoBeR182** [comment]
@BastienLQ Do you think you could incorporate @jpfox lock icon. It makes sense in my head for a lock to be more secure then a keyhole.

**Comment by jpfox** [comment]
Using Google guidelines, I've got this icon (with a color from Google palette)
![smssecure-material](https://cloud.githubusercontent.com/assets/5191640/6786002/aa30b2a4-d189-11e4-8eba-032ee7056374.png)

**Comment by jpfox** [comment]
Using Google guidelines, I've got this icon :
![smssecure-material](https://cloud.githubusercontent.com/assets/5191640/6786050/12f26706-d18a-11e4-96ff-c0e64c572697.png)

**Comment by SecUpwN** [comment]
Hey there folks, awesome progress here! :smiley_cat: @jpfox, all of your mockups are great, but I would like to avoid people complaining that the Icon looks "too similar" like TextSecure. I am voting **against** using the TextSecure Icon as proposed in https://github.com/SMSSecure/SMSSecure/issues/18#issuecomment-84999255 - not only because it is just a color change, but also using wrong dimensions (which I previously filed in https://github.com/WhisperSystems/TextSecure/issues/2534).

So here is my recommendation: Use color `#00CC00` since it makes the Icon look serious, yet friendly. But please add some "uniqueness" to it! I mean, how many Apps are out there showing a speach bubble with a lock in it? Boring. From the work you've presented here, I know that @jpfox can be a little more creative, right? Let's collect an idea first! How about a Lock on a Fork (indicating that the App has been forked, but still encrypting things), @johanw666? We're allowed to get a little crazy here.

**Comment by jpfox** [comment]
Two new models...

"bi-green" :
![smssecure-4](https://cloud.githubusercontent.com/assets/5191640/6802109/e8a7d1ee-d22d-11e4-8582-36b26f46ccab.png)

 and "forked-green" :
![smssecure-5](https://cloud.githubusercontent.com/assets/5191640/6802110/ecb52598-d22d-11e4-9a75-be61d471f032.png)

I'm waiting for your comments to improve this icon

**Comment by BoBeR182** [comment]
Single-fork-green a possibility? That would be my vote.

**Comment by BastienLQ** [comment]
I prefer [this one](https://github.com/SMSSecure/SMSSecure/issues/18#issuecomment-85113276), with a shadow, and maybe a smaller padlock and `#7568ae`.

**Comment by pR0Ps** [comment]
I'm not fond of the fork icon. This app is for the average user who has no idea what fork means, nevermind the fact that this icon represents one.

I also like the keyhole icon more than the lock. Locks are way overdone and there are enough of them in the app already. The icon needs to differentiate itself from every other "secure ______" app out there.

There are a few apps on the play store that have really nice material icons. [Hangouts](https://lh6.ggpht.com/5puZavg4x2pThSTJgos1sARWoARea7tzr_B8AWEwn2lV05RoXo9M8BM2XwcvwG6nIGc), and [Messenger](https://lh5.ggpht.com/GEWb6ZYNQpE5lGgnRSXkG_UePDR-qcVqOYBZbMfiYGxCuR2FrtXXpElvqVuAM65usQN0), and [EvolveSMS](https://lh5.ggpht.com/SH0GFeQzs7w6RZoQ5PIxndvUPvoB1PB8eW_p28oeiRzw8P0MOThX_n_6H0iuJ1LKD9FT) to name a few.

Hangouts we probably shouldn't use with the keyhole icon because it'll look too similar to TS, but I think something like the messenger icon (maybe the just the blue box with a raised keyhole + shadow on it) would look really slick, be different enough from TS, but give a nod to it's roots with the keyhole icon.

Using the resources of the parent project (https://www.pixelapse.com/openwhispersystems/projects/signal-android/views/assets/) would be a good place to pull the keyhole shape and shadow from.

**Comment by jpfox** [comment]
I think key hole is not reassuring : you use it to spy what happens in a room you are not allowed to go.
Maybe a key could be an other idea but it is overused by many apps (as the lock).
IMHO, this new icon must be as different as possible from TextSecure one.
For the color, green looks like a toy apps for me, a purple as @BastienLQ propose #-7568ae looks more serious.

So there is three things to determine
- the global shape : round, rectangle or square
- the main symbol : lock, key, keyhole or something else evoking security
- the color : pick from previous propositions or give a new one from Google guidelines http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by BastienLQ** [comment]
I agree with @pR0Ps that Material icons like Messenger or EvolveSMS are really nice. And I also like the keyhole because every "secure" app puts a padlock on its icon, so it's not uncommon anymore.
And yes, greens is too flashy in my opinion.
The main symbol should really be a keyhole. For the global shape, a rectangle (or 2) inspired by EvolveSMS. For the color, not green (@jpfox could you try with `#7568ae`?)

**Comment by SecUpwN** [comment]
Whoa, slow down a bit - we don't want @jpfox to drown in crafting Icons! ;-)

Generally speaking, I like:

* Round shape, avoid another "speech bubble"
* Serious color (please don't do Windows8 style)
* [Wasabeef's Awesome Android UI](https://github.com/wasabeef/awesome-android-ui)

Other than that, I am open for everything. And hey, in https://github.com/SMSSecure/SMSSecure/issues/18#issuecomment-85485522 the "forked-green" doesn't look too bad (excpet for the color, I now realize it's hurting the eyes). But when I said "fork", I actually meant a **real fork/pitchfork** - maybe just replace the keyhole of the lock with a FORK in horizontal view?

![Pitchfork](https://commguide.asu.edu/files/images/General_Pitchfork_2C.jpg)

**Comment by BoBeR182** [comment]
#9c27b0 on a single-forklock-speech bubble would cool. I prefer it over the discussed #7568ae.

**Comment by johanw666** [comment]
I built a version based on the 0.3.3 source with the purple mirrored TextSecure icon. I think it looks quite nice, I'll just have to replace the other blue elements with purple too to make it look consistent. I'll work on it a bit more. I can build a version with another icon to compare. I put my initials in the version number to make it clear it is no official version but I kept the build number te same. It does have a different signature of course, so backup and reinstall is required unless you use software that disables Android's signature check like LuckyPatcher.

http://johanw.home.xs4all.nl/SMSSecure-0.3.3.2-JW-release.apk

**Comment by jpfox** [comment]
Let's call them respectively blue, purple and green square-bubbles-keyhole !
![smssecure-6](https://cloud.githubusercontent.com/assets/5191640/6824894/7c1bde66-d2f6-11e4-848d-47c27ea0dfb7.png) ![smssecure-7](https://cloud.githubusercontent.com/assets/5191640/6824896/81441bc4-d2f6-11e4-979d-72a6c9207cef.png) ![smssecure-8](https://cloud.githubusercontent.com/assets/5191640/6824901/8717c212-d2f6-11e4-9fbf-57dc0aed89ea.png)

I've changed keyhole shape to not look too close to TextSecure icon.

**Comment by steinhmor** [comment]
@jpfox I like the new shape very much!
Perhabs other colors like Amber, etc. should also be tested... in my eyes this would look a bit more friendly and fresh

**Comment by pR0Ps** [comment]
A quick hack on @jpfox's latest (I am not good with manipulating pixels):
![quick hack](https://cloud.githubusercontent.com/assets/466941/6828334/9fbb4f18-d2e3-11e4-9ba0-be216ab589e6.png)

Notice:
 - Keyhole icon is flattened into the background (like the white text in [Messenger](https://lh5.ggpht.com/GEWb6ZYNQpE5lGgnRSXkG_UePDR-qcVqOYBZbMfiYGxCuR2FrtXXpElvqVuAM65usQN0))
 - Keyhole icon is the same shape as TextSecure's (with the different shaped backing, different size, different color, and lack of height on it I feel like we're different enough)

Changes needed:
 - Lack of shadow on the backing bubble
 - Remnants of purple on the keyhole from copy-pasting from [this icon](https://github.com/SMSSecure/SMSSecure/issues/18#issuecomment-84999255) :)

Possible alterations:
 - Colors
 - Size of the keyhole
 - Make the backing bubble more neutral (see Messenger design)
 - Put a partially-obscured or lines of text keyhole on the backing bubble (will need to change offset)

Thoughts?

**Comment by SecUpwN** [comment]
>Thoughts?

Great work @jpfox and funky edits @pR0Ps! I would also vote for putting a partially-obscured or lines of text (preferrably signs that look like encryption) on the backing bubble. As for the improvement of the Icon itself, please get inspired [here](https://github.com/wasabeef/awesome-android-ui)!

**Comment by johanw666** [comment]
I updated the version with the mirrored TextSecure icon to have purple colors in the bar above the program as well. And I made a version with the purple version of the last icon set that @jpfox posted here. Apart from the icon and version number the source is the same, so you can check how you like the icons in practice.

http://johanw.home.xs4all.nl/SMSSecure-0.3.3.3-JW-release.apk
http://johanw.home.xs4all.nl/SMSSecure-0.3.3-icon_jpfox-release.apk

**Comment by jpfox** [comment]
If you want I prepare a pull request with a specific icon, let me know...

**Comment by BastienLQ** [comment]
Yes, with the @pR0Ps version, please.

**Comment by jpfox** [comment]
I need some help... I've replaced all icon.png & icon_dialog & lockscreen_watermark.png in res/drawable* directories and rebuilt with gradlew clean / gradlew build
The new apk seems to have always the old icon ??
Is there a command to apply change before gradlew build ?

My commit : https://github.com/jpfox/SMSSecure/commit/2a9e4df78d56218c158b8d9575daee1871ef387e

**Comment by BastienLQ** [comment]
Did you run `./gradlew clean` before?

**Comment by jpfox** [comment]
Yes, I have... but I haven't transfer the good apk on my device... It's time to go to bed !
I prepare the pull request

![smssecure192](https://cloud.githubusercontent.com/assets/5191640/6837452/959e87fc-d34c-11e4-9888-48e2d7a2c74b.png)

**Comment by johanw666** [comment]
You can change the program colors in /res/values/colors.xml. It's in several places there.

**Comment by BastienLQ** [comment]
@jpfox Could you please provide an icon in purple (based on `#7568ae`) and with a flattened keyhole (no shadow)?

**Comment by jpfox** [comment]
#7568ae is not a color from Google guidelines. Same thing for shadow, Google explain that icons must have two layers and a shadow from the foreground layer on the background layer.
But I could provide a such icon if you want.

Do you want a pull request or just a png ? (generate all sizes for app is long, so if it is not necessary...)

**Comment by johanw666** [comment]
"generate all sizes for app is long"

I used just Paint Shop Pro to resize the icon from 192 to the smaller sizes and copied the right size into the lockscreen images. Didn/t take too long, and if you start with the highest resolution icon that doesn't need to be made larger it doesn't take too much time. I'm sure that can be done better but good enough for a test version IMO.

**Comment by BastienLQ** [comment]
Just a PNG to make comparisons.

**Comment by jpfox** [comment]
![smssecure10-192](https://cloud.githubusercontent.com/assets/5191640/6855766/5e2785a8-d3fb-11e4-8548-1403560aa0c9.png)![smssecure10-192-flat](https://cloud.githubusercontent.com/assets/5191640/6855780/76ab154a-d3fb-11e4-92ae-bf3c90f7fead.png)![smssecure11-192](https://cloud.githubusercontent.com/assets/5191640/6855786/82a3b74e-d3fb-11e4-8566-31140465d91c.png)

**Comment by BastienLQ** [comment]
I love the middle one.

**Comment by BastienLQ** [comment]
But with a shadow behind squares, that would be better (a mix between the first and the second, with a flatten keyhole but squares with shadows).

**Comment by steinhmor** [comment]
@jpfox what about trying to take the middle one and cut out the keyhole so you can see the second bubble through it (perhaps with encryptet signs in it)

**Comment by BastienLQ** [comment]
Maybe for a future icon. For now, as we would add SMSSecure in F-Droid and in the Play Store, we need a new icon quickly.

**Comment by SecUpwN** [comment]
Please use one **WITH** shadow! :+1:

**Comment by jpfox** [comment]
I'm sorry for delay, I'm few busy this moment : working, entirely renovating a house, 4 children at home and getting married in two weeks !
So if someone can replace actual icons by this one, after resizing if necessary. You can see what to do in this pull request : https://github.com/jpfox/SMSSecure/commit/2a9e4df78d56218c158b8d9575daee1871ef387e
![smssecure-12](https://cloud.githubusercontent.com/assets/5191640/6877398/084687ac-d4d1-11e4-8a5b-905acf2acda1.png)

**Comment by jpfox** [comment]
If you want you could also replace some small icons in black and white (yes there is a white icon with transparent key hole under black one).
![smssecure-mono-b-64](https://cloud.githubusercontent.com/assets/5191640/6877592/a80e5ebc-d4d2-11e4-86a2-eb2dbc26b41e.png)
![smssecure-mono-w-64](https://cloud.githubusercontent.com/assets/5191640/6877593/b3a3c62c-d4d2-11e4-8bbb-ca6233336c3f.png)

**Comment by johanw666** [comment]
The several actionbar_icon_holo_light.png icons might also be replaced - they are still in TextSecure <= 2.4.2 style.

**Comment by pR0Ps** [comment]
@jpfox I can do the resizing and everything, but could you provide your source files for the images?

**Comment by BastienLQ** [comment]
@jpfox Any news? We're waiting for your icon before publishing SMSSecure in F-Droid. ;-)

**Comment by SecUpwN** [comment]
>We're waiting for your icon before publishing SMSSecure in F-Droid. ;-)

Please also create an official store on [Aptoide](http://www.aptoide.com/) and publish it there!

**Comment by BastienLQ** [comment]
@SecUpwN I update #4.

**Comment by jpfox** [comment]
Oups, sorry, https://cloud.o123.org/owncloud/public.php?service=files&t=d5282b2179ef34e14aec2043ed42170b

**Comment by BastienLQ** [comment]
@jpfox Could we have the SVG of this? https://cloud.githubusercontent.com/assets/5191640/6877592/a80e5ebc-d4d2-11e4-86a2-eb2dbc26b41e.png

**Comment by jpfox** [comment]
of course : https://cloud.o123.org/owncloud/public.php?service=files&t=5782feb24859f2852151a90912dac46d

**Comment by BastienLQ** [comment]
Thanks. And the white version?

**Comment by jpfox** [comment]
Here : https://cloud.o123.org/owncloud/public.php?service=files&t=9a78fec7c28322b6d51752401e0ab6c2

**Comment by jpfox** [comment]
And grey 50% : https://cloud.o123.org/owncloud/public.php?service=files&t=7943c3a6e81709aca585e8077966ae2a

**Comment by BastienLQ** [comment]
The grey used in the original icon is `#9c9c9c`. Could you update your SVG with that hex color?

**Comment by BastienLQ** [comment]
Well... In fact the original black icon uses `#2f2f2f`.

**Comment by BastienLQ** [comment]
And your first link is the PNG version. ;-)

**Comment by jpfox** [comment]
ok, i put 3 in same svg file #2f2f2f / #9c9c9c / #ffffff

https://cloud.o123.org/owncloud/public.php?service=files&t=e4724967b0aa11da46a57849f458d5e2

**Comment by BastienLQ** [comment]
Thanks!
