### ISSUE TITLE
Apple emoji?

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#181]
I saw that TextSecure is now using the Apple emojis in their development version (commit https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613). I asked on their mailing list wether this means they are really free and can be used in other projects like SMSSecure too, but I received no answer yet. Does anyone here knows something about that? I thought those were not free to use but like to be proven wrong.

**Comment by BastienLQ** [comment]
Good question. We won't merge this commit until we're sure we can reuse assets. Additionally, as SMSSecure is not and will never be ported to iOS, we could keep Android's emojis. @pR0Ps?

**Comment by pR0Ps** [comment]
My opinion would be to not pull in the change at all. TextSecure made the change because they needed to standardize on an emoji set across all platforms. Since we only need to support Android it makes sense to just keep the Android ones.

**Comment by johanw666** [comment]
This will affect other upstream commits as well, like https://github.com/WhisperSystems/TextSecure/commit/282f139ee9f9483a49ac78f448d1e2d3bbb5e374 and I'm not sure about https://github.com/WhisperSystems/TextSecure/commit/9b2aabfdc8ece6c1002176ae75abe98229a46054

**Comment by BastienLQ** [comment]
I agree with you, @pR0Ps; I won't merge upstream commits related to emojis in #180.

**Comment by AtomiKe-FR** [comment]
Can we choose between Apple emojis and Android emojis?
Some people prefer the Apple ones.

**Comment by BastienLQ** [comment]
License for Apple's emojis is unclear, so we can't use them.

**Comment by oxodao** [comment]
How about letting the user set his ttf file for emoji ? I'm currently testing "EmojiOne" that could be could either letting the user choose or adding it to Silence :)
