### ISSUE TITLE
question: Will SMSSecure work alongside Cyanogenmod's WhisperPush?

### ISSUE THREAD

**Issue by ericfont** [SMSSecure/SMSSecure#183]
If I install SMSSecure on a Cyanogenmod phone, will I be able to send/receive secure SMS messages to people that use SMSSecure AND send/receive secure (non-SMS) texts to people that use TextSecure?

**Comment by johanw666** [comment]
If WP on CM works as TS now, that should be possible. You can expect a warning in WP about a non-supported protocol when you receive an encrypted sms but you can ignore that, it should show up in SMSSecure anyway.

**Comment by BastienLQ** [comment]
I don't know how WP sends messages to TS users but I suppose it will work, maybe with the same bug as in #6. Your feedback would be interesting for us. ;-)
