### ISSUE TITLE
MMS : sent only with Wi-Fi enabled

### ISSUE THREAD

**Issue by Kdmeizk** [SMSSecure/SMSSecure#189]
- SMSSecure can only send/receive MMS when Wi-Fi is enabled
-> MMS don't work if Wi-Fi is disabled, even if data connexion is enabled or not.

 - SMSSecure uses data connexion when Wi-Fi is enabled
-> It uses data connexion + Wi-Fi or only data connexion with Wi-Fi enabled, it's really strange.

Android 4.1.2
Samsung Galaxy Ace 2

**Comment by pR0Ps** [comment]
Related to https://github.com/SMSSecure/SMSSecure/issues/68
