### ISSUE TITLE
Do you provide interfaces to access the encrypted storage and get notified of incoming messages, for remote backups ?

### ISSUE THREAD

**Issue by jeekajoo** [SMSSecure/SMSSecure#192]
Hi,

Today I'm not using SMSSecure because I can't backup my SMS.
I'm using the stock SMS app, forked by omnirom, along with sms-backup-plus (https://github.com/jberkel/sms-backup-plus).

So my question is: 
Do you provide interfaces to access the encrypted storage and get notified of incoming messages, for app like sms-backup-plus to backup ?

Thanks
J.

**Comment by nepda** [comment]
I want to use SMS Backup and Restore [1] but this tool is not able to read the SMS. Or is there another possibility to schedule backups?

1. https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore

**Comment by johanw666** [comment]
You need to do a plaintext export from SMSSecure, SMS Backup and Restore is then able to read that plaintext export. It can't read the SMSSecure database directly.

**Comment by pR0Ps** [comment]
See also #144, #192
