### ISSUE TITLE
Emoji icon disable

### ISSUE THREAD

**Issue by Nomeji** [SMSSecure/SMSSecure#193]
Add an option to disable emoji icon on message text entry.
The icon is taking 10% of the text box for a never used icon and it's already in most keyboards apps.

**Comment by johanw666** [comment]
It should not leave entirely, my keyboard (Hackers keyboard, https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) does not have any emoji key (but some other keys most other keybioards have niot).

**Comment by BastienLQ** [comment]
The idea is to add an option to disable Emoji's pane, but keeping this pane enabled by default.

**Comment by pR0Ps** [comment]
I like this. A lot of keyboards already have an emoji drawer built in (usually accessible via holding the return key) and having 2 different drawers is confusing (different layout, different "recently used", etc).

An option to simply hide the emoji button and only use the keyboard emoji would be great.
