### ISSUE TITLE
Feature Request: Chat without GCM

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#20]
Good evening @SMSSecure developers,

thank you so much for this fork of the original TextSecure App! Let me tell you that there are thousands of people out there searching for an alternative to TextSecure now. With great interest I stumbled upon your fork here and noticed that you stated `Drop Google services dependencies: push messages are not available in SMSSecure; if you want to keep them, SMSSecure is not for you.` Great stuff!

Although my focus also lies on encrypted SMS, I am opening this Issue to discuss a possible chat *without GCM**. That means, if SMSSecure would be granted internet access, you could chat with each other just like in a chat room. Again, all of this should be done without Google and does **NOT** have to implemented right away, it's just a request and small glimpse of hope in my ongoing search for the "perfect crypto-messenger" which would cover both types of communications while being open source.

One more important thing: You should add your App to the [Secure Messaging Scorecard](https://www.eff.org/secure-messaging-scorecard)! Thank you!

**Comment by BastienLQ** [comment]
TextSecure currently use GCM, but they will provide a new push message service through websockets and federated servers. So what you are looking for will be done in TextSecure.

SMSSecure focuses on SMS only. That's why TextSecure is not be incompatible with SMSSecure (the current limit is #6).

**Comment by SecUpwN** [comment]
That kinda sucks. It looks like I'm forced to use TextSecure and use SMSSecure as an "addon".. :(

**Comment by BastienLQ** [comment]
SMSSecure is not designed to be perfect, just because metadata are leaked (by your ISP, your phone operator or Google). Even TextSecure with push messages is not 100% perfect, thus you are not forced to use TextSecure. You may consider using XMPP+OTR+Tor or something like that if you want to improve your privacy. Do not trust neither SMSSecure nor TextSecure to be hidden, they just provide a way to encrypt your conversations.

**Comment by SecUpwN** [comment]
>SMSSecure is not designed to be perfect, just because metadata are leaked...

No, I never requested SMSSecure to be perfect. I am just looking for the "best bet" in terms of having **ONE** App that can actually communicate via encrypted SMS, but is also capable of providing a chat room that works without any GApps once it is online. Furthermore, the App shall be fully open source and carefully maintained. And that is where I was having high hopes SMSSecure could jump in, hence I recommended it on [Heise](http://www.heise.de/security/news/foren/S-Re-empfehlenswerte-Android-app-fuer-vollstaendige-Verschluesselung/forum-283367/msg-26658790/read/showthread-1/) (see the traffic of your repository, I hope I have drawn some attention to your fork here). To be perfectly honest with you: I would be very grateful if you could reconsider adding such a chat room and make SMSSecure even "better" than TextSecure. I could help you finding a few more developers if you plan to do this.

**Comment by invapid** [comment]
"SMSSecure focuses on SMS only"

this is a fundamentally flawed project
* it's adding layers of hacks to antiquated technology. 
* we need to be moving away from SMS, not trying to support it.
* moving away from SMS reduces dependency on the telecom industry

better solutions
* work on increasing usability on textsecure
* merging textsecure + redphone to better compete with voxer, whatsapp, telegram, hangouts and friends

**Comment by pR0Ps** [comment]
@invapid: It sounds like you want something exactly like [TextSecure](https://github.com/WhisperSystems/TextSecure). Please use and contribute to it - it's a great app.

@SecUpwN: The goal of SMSSecure isn't to be better than TextSecure. It's only goal is to support encrypted SMS for people that don't want to/can't communicate over data. Also, push chat is hard. There's a reason TextSecure devs are using GCM to help. This isn't something that's in our scope.

**Comment by landry314** [comment]
I need SMS Encryption so I plan on using SMSSecure. If you want encryption over data, use TextSecure or ChatSecure or any OTR Client. You can have all these apps running in parallel. The more people encrypted the better! I don't have a data plan or Gapps on my phone so I need SMS encryption and I am very happy this fork is moving along so well!

**Comment by mejo-** [comment]
Just wanted to add that I'm very happy about the devs choice to focus on encrypted SMS feature. For encrypted communication over data, other great apps like TextSecure, Conversations or ChatSecure exist. Thanks for continuing support for encrypted SMS now that it has been ripped out of TextSecure.
