### ISSUE TITLE
Websocket support // fork is on its way // please integrate

### ISSUE THREAD

**Issue by jusa213** [SMSSecure/SMSSecure#200]
One of the main reasons SMSsecure was created is the use of google play service in textsecure (and of course the lack of encrypted SMS in recent text secure versions).
Saying this SMSsecure as a project is much appreciated.

What is lacking until right now is the full spectrum of features that Textsecure provides.
As it seems there is a fork of the push feature going on and websocket support is on it's way.

Please check that out and think about an integration into SMSsecure.

More info to be found here:
https://github.com/JavaJens/TextSecure/wiki/Building-the-Websockets-reborn-fork

P.S.: I am not affiliated with that project.

**Comment by pR0Ps** [comment]
SMSSecure does SMS only, we're not going to add support for internet-based messaging.
