### ISSUE TITLE
Notification sound rings twice per message

### ISSUE THREAD

**Issue by breversa** [SMSSecure/SMSSecure#203]
Hi there,

I'm using SMSsecure 0.10.1 (from F-Droid) on my Samsung Galaxy Nexus (maguro) running CyanogenMod 11-snapshot (= latest version to date).

I noticed that when I get a new message, the notification sound (and vibrating too, but I need to confirm that) rings twice. However, it's not one ring after the other : it is as if the first ring is interrupted by the second.
It's hard to explain a sound with word, but I'll try to give an example : if my notification sound rings "ding dong", I won't hear "ding dong ding dong", but rather "di-ding dong".

It happens regardless of the "in-conversation notification" option being on or off.

Any idea ?

**Comment by johanw666** [comment]
This used to plague TextSecure for quite some time, however they have solved it in most cases. See for example the discussion in https://github.com/WhisperSystems/TextSecure/issues/2148

**Comment by breversa** [comment]
Thanks @johanw666 for your timely reply.
I tried to set the notification repeat from one and back to zero, but to no avail. :-(

Any way I can help troubleshoot that issue ?

**Comment by hakcenter** [comment]
I'm having the same exact issue. 

On top of that tonight, randomly even though i have do not disturb on, which disables notification  sounds etc...  Randomly some will make noise and when it does I get the double noise.

I imagine it's related to the popup which apparently is unable to be disabled.

**Comment by dolohow** [comment]
I can confirm that issue is still in the latest version.

**Comment by zoff99** [comment]
that bug is still there in the latest f-droid version.
it happens every time i receive an sms.
it sounds like the sound is played 2 times, the second one following very shortly after the first one.
then the two sounds overlap.

very annoying ::-(

**Comment by scienmind** [comment]
Joining the complain club here:

Exact same issue here, with latest F-Droid build (Version 0.12.3) (using on CM12.1).
Signal (a.k.a TextSecure) don't have this issue with SMSs, maybe upstream will fix it?

Anyways, the double-ringing is indeed annoying, I hope you guys will find the fix :-)

**Comment by Yankee14** [comment]
Same here. Whether or not a ringtone plays once or twice is a hit-or-miss.

Is the problem that the Android OS settings has its own notification settings, independent of SMS Secure? I seem to be able to set one notification ringtone in Android, and another, different notification ringtone in SMS Secure.

Sometimes the notification plays once (properly, as it should), sometimes plays twice, and sometimes it fails to play any sound at all.
