### ISSUE TITLE
Fix Chinese translations

### ISSUE THREAD

**Issue by xumiy** [SMSSecure/SMSSecure#205]
When I set Chinese in the app,it still shows English.
The folder /res/values-zh_CN and /res/values-zh_TW should be rename to /res/values-zh_rCN and /res/values-zh_rTW to fix it.
Seeing http://stackoverflow.com/questions/17843903/chinese-locale-values-zh-cn-gives-an-error-on-eclipse

**Comment by xumiy** [comment]
http://stackoverflow.com/questions/4189875/simplified-and-traditional-chinese-vs-regions

**Comment by BastienLQ** [comment]
Already fixed in 3bf649e3c0e7678fae91df91842d0e9a85b8f469.
