### ISSUE TITLE
TeslaUnread Support

### ISSUE THREAD

**Issue by twprogrammers** [SMSSecure/SMSSecure#208]
I would like TeslaUnread support added.

**Comment by BastienLQ** [comment]
Details?

**Comment by twprogrammers** [comment]
It's a unread count system. Works with several very popular launchers and such.

https://play.google.com/store/apps/details?id=com.teslacoilsw.notifier

**Comment by BastienLQ** [comment]
We removed ShortcutBadger and won't readd this functionality. You can get the number of unread messages in notifications.

**Comment by twprogrammers** [comment]
May I ask *why* it was removed?

**Comment by BastienLQ** [comment]
Because you can have the number of unread messages in the notification.

**Comment by ToNIX-** [comment]
Bumping this, I'd like to have this added. It worked for a while, but stopped working recently.
