### ISSUE TITLE
General rules for translations?

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#213]
I opened the same issue in upsream: https://github.com/WhisperSystems/TextSecure/issues/3863 because it applies to both.

I'm on the translate team for TextSecure and SMSSecure for the Dutch language, and I noticed in both projects some inconsistencies. In Dutch, you have 2 forms for the English "you" (ignoring the "thou" form here): the informal "jij", and the more formal "u". I noticed both forms are used in translations, probably depending on the personal preference of the translator of the specific string. In French you have "tu" and "vous", in German "du" and "sie", but I didn't check the French and German translations to see if the forms are mixed there too. I don't know any other languages well enough to say if it can be an issue there.

In current Dutch both forms are socially acceptable (although some mostly elder people frown on the use of the informal form).

I would suggest the app choose one of the forms to be more consistent. Having both forms mixed makes a sometimes strange impression. I have no strong personal preference for either form.

What is the opinion of the developers?

**Comment by BastienLQ** [comment]
It depends. ;-)
Each language have its preference but you must not use both. In French, the formal form is always used, but not in Italian.
