### ISSUE TITLE
Add an option to toggle automatic MMS retrieve (Stagefright vulnerability)

### ISSUE THREAD

**Issue by halcyonest** [SMSSecure/SMSSecure#216]
While many stock and 3rd-party SMS/MMS clients provide an option to toggle automatic MMS retrieve, SMSSecure doesn't have this feature. As a temporary but effective countermeasure against Stagefright vulnerability, SMSSecure needs to adopt this feature as soon as possible.

**Comment by johanw666** [comment]
Double of https://github.com/SMSSecure/SMSSecure/issues/211
