### ISSUE TITLE
No phone lock detection on Lollipop

### ISSUE THREAD

**Issue by TheMrNomis** [SMSSecure/SMSSecure#219]
Hi,

When the SMSSecure app is opened, and then the phone is locked, SMSSecure does not seem to detect the lock : no notifications are displayed (just a sound when the phone is not on vibrate mode), and the application does not lock itself with the password.

I'm running SMSSecure 0.10.1 (build 16e0618) on Lollipop 5.1.1 on a moto G 3rd generation, with Dodol launcher and the default locker.

I didn't have this bug on my old phone (Wiko darkside running Jelly bean 4.2.1, SMSSecure 0.10.1 build 16e0618, with dodol launcher & dodol locker)

**Comment by BastienLQ** [comment]
Can you attach a debug log, please?

**Comment by TheMrNomis** [comment]
Sure : https://gist.github.com/anonymous/04b62747926f6322838d

**Comment by BastienLQ** [comment]
Did you lock SMSSecure and receive a message before submitting this debug log?

**Comment by TheMrNomis** [comment]
No, I locked my phone while SMSSecure was the active application, and waited more than the password's expiration time (1mn in my case), then unlocked the phone, and SMSSecure was still unlocked.

But, as I made a few tests, it seems that the bug is caused by the "moto screen" (an application by motorola that replace the locker when receiving notifications), because when this screen is disabled, the bug doesn't show anymore.
