### ISSUE TITLE
Add option to have emoji button directly on the keyboard (like hangouts)

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#223]
After some experimentation it seems like with most keyboards the emoji button can be directly added to the keyboard (instead of being hidden behind the enter key) by specifying that the type of the input box is a short message.

Idea for implementation (not tested extensively) - in `ComposeText.java` on [this line](https://github.com/SMSSecure/SMSSecure/blob/f89ab056b8885b14d340927be83d61ff0ec27a30/src/org/smssecure/smssecure/components/ComposeText.java#L78):
```
inputType = !showEmojiKey
          ? inputType & ~InputType.TYPE_TEXT_VARIATION_SHORT_MESSAGE
          : inputType | InputType.TYPE_TEXT_VARIATION_SHORT_MESSAGE;
```

I propose the following options structure:

Conditions for enabling options:
 - *Disable Emoji drawer* option:
   - Always enabled
 - *Show emoji key instead of enter* option:
   - Enabled only when *Disable Emoji drawer* is on
   - When the emoji drawer is enabled, there's no need to have the emoji button on the keyboard as well.
 - *Enter key sends* option:
   - Enabled when *Disable Emoji drawer* is on OR *Show emoji key instead of enter* is off
   - When the emoji drawer is disabled, the user can choose if they want to have the enter key send or insert a newline (emojis will be on long tap).
   - When the emoji key is shown instead of the enter key, there is no enter/send button so this setting would do nothing.

**Comment by johanw666** [comment]
I use a keyboard (Hackers keyboard) that does not support an emoji key. In the reasoning above, the enter is send option would always be on on my setup. Why would that be needed? The current situation works fine for me: emoji button in the type area and enter is send off.

**Comment by pR0Ps** [comment]
Nothing is changing by default, you would now just have the choice of enter = send/newline/emoji

The problem with the emoji button in the text box is that it loads an in-app emoji drawer instead of the keyboard one. For people that are used to inserting emojis from their keyboards this is a bit annoying. Plus, it takes up space in the text box and can make things cramped for smaller screens.

**Comment by johanw666** [comment]
Sorry, then I misunderstood the logic you explained. It reminded me of the times I had no emojis at all in TextSecure on Kitkat (well, I hacked it back in myself but by default I didn't have them).
