### ISSUE TITLE
Make SMSSecure easily findable on Github

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#232]
When I go to www.github.com and search for SMSSecure, I see:

Abner87/SMSsecure
blackcatdead/smssecure
aquaxp/android_packages_apps_SMSSecure
SMSSecure/smssecure.org

But I DON't see SMSecure/SMSSecure. Somehow something has been messed up, and perhaps I should report this to Github itself.

It also makes opening the repository through the Forkhub Android client a bit tricky (I bookmarked it now),

**Comment by pR0Ps** [comment]
Because it's a fork, you need to search for "SMSSecure fork:true". Unfortunately this is just how GitHub works. Also, contributions to SMSSecure don't show up in profiles for the same reason.

**Comment by johanw666** [comment]
I do see SMSSecure/SMSSecure in the list of "repositories contributed to" when I check my profile. Or did you mean something else?

I will file an issue with Forkhub to add this option, since they themselve are a fork (of an abandoned project) I hope they'll understand.
