### ISSUE TITLE
Sending sms no longer possible

### ISSUE THREAD

**Issue by ajolivet** [SMSSecure/SMSSecure#251]
Hi,

I'm unable to send sms texts anymore with smssecure. It works fine with the default application and I can still receive fine with both.
The texts stay in the status: pending.
I have a firewall but even with allowing smssecure it doesn't work (my firewall is probably not the issue though since it was working fine before, even with smssecure not allowed).
I've tried updating and reinstalling the app, same problem.
I have a Wiko Cink Peax 2, the version of smssecure is 0.11.3.

Thanks for your attention.

**Comment by BastienLQ** [comment]
Did you move the SIM card from slot 1 to slot 2? Also, a debug log would be useful.

**Comment by ajolivet** [comment]
Yeah, it must have been what caused the problem, because when I switch back it works fine. Thanks for your help.

**Comment by BastienLQ** [comment]
Duplicate of #86.
