### ISSUE TITLE
Switch off sending autodetection marker in settings

### ISSUE THREAD

**Issue by kkovacs** [SMSSecure/SMSSecure#253]
Hi guys,

I understand that SMSSecure sends some kind of "marker" in normal messages, so if SMSSecure is installed on the other side, it can offer to start a key exchange.

It would be good if there would be an option in Settings to switch off this marker, since it possibly leaks information of one using SMSSecure to everybody.

Please correct me if it's not working like this!

(Keep up the good work!)

**Comment by BastienLQ** [comment]
The marker only consist of 10 whitespaces at the end of each non encrypted message. This tag is too common to be used as a tracker.

**Comment by kkovacs** [comment]
Dear Bastien, thank you for your reply!

What do you mean by "too common"? I don't know of any other plausible reason why would I have exactly 10 empty spaces at the end of all my messages... :)

Are you sure there's absolutely no value in being able to switch off the sending of the marker...?

Keep up the good work anyway -- great project!

**Comment by BastienLQ** [comment]
SMS apps on dumbphones sometimes add whitespaces at the end of messages. Not 10, I agree, but using on this tag to track SMSSecure users is not reliable.
