### ISSUE TITLE
Can't send or receive MMS when WiFi off

### ISSUE THREAD

**Issue by RobHot** [SMSSecure/SMSSecure#257]
Hi everybody and sorry for my english.

To begin I have to congratulate you for this project and for all your work.

SMSSecure works good for all activities about SMS.

I tried to send or receive MMS like tests described below : 
- My phone with SMSSecure can't send MMS
- My phone with SMSSecure can receive MMS from another phone with stock SMS Apps
- My phone with Stock SMSApps can send MMS

I've seen in parameters : Manual MMS parameters.

It seems, I can't set the same parameters than my APN.

My APN :
Name : MMS Leclerc Mobile
APN : mms66
Proxy : Not defined
Port : Not defined
Name of user : Not defined
Password : Not defined
Server : Not defined
MMSC : http://mms66
Proxy MMS : 10.143.156.9
MMS port : 8080
MCC : 208
MNC : 10
Authentification type : PAP
APN type : mms
APN Protocol : IPv4
Enable/Disable APN : Enable
Network : Not specified
MVNO type : None
MVNO value : Not definied

SMSSecure Manual MMS parameters : 
URL MMSC : http://mms66 (personalized)
MMS proxy server : 10.143.156.9 (personalized)
MMS proxy port : 8080 (personalized)
MMSC User Name : None (by default)
MMSC Password : None (by default)
MMS User Agent : Android-Mms/2.0 (by default)

What could I do ?

my phone : Galaxy S3 16Go Intl
my rom : Cyanogenmod 10.2.0-i9300
my country : France

**Comment by RobHot** [comment]
Today, after my update i try to send MMS and it is successful.

And I remember #189 and #68 what i read yesterday.

I try Wifi off and it didn't work, that confirms what I read.

I've the same problem with #189 and the opposite to #68 .

In common is android 4.1.2 among other.

But it's not that the problem.

That is my APN parameters : 
Authentification type : 
     - old : PAP
     - new : None
APN type : 
     - old : mms
     - new : default,mms

Everything works well, sorry for my post.

I still congratulate you for your work, continue !

**Comment by AmadekCom** [comment]
Silence 0.14.3
Phone: Honor 5X

I have the same problem. I can not receive and send aby MMS.
When I use standard app "Message" MMS works good. I am sure this is a problem with Silence.
