### ISSUE TITLE
To Restore User's Ability to Regenerate Identity Key

### ISSUE THREAD

**Issue by optimumpr** [SMSSecure/SMSSecure#26]
Moxie has removed that ability after 1.0.6 version.  For reference on the evolution of the original Textsecure project see here:

https://f-droid.org/forums/users/optimumpro/replies/
http://forum.xda-developers.com/showthread.php?t=2669372
http://forum.xda-developers.com/showpost.php?p=59639423&postcount=163

**Comment by johanw666** [comment]
I think this should be combined with #16

**Comment by pR0Ps** [comment]
The [commit message from Moxie](https://github.com/WhisperSystems/TextSecure/commit/6b5753337c9df2b53aed9ea2e2d9d5d8d037b2f2) says why he chose to remove it and honestly, I agree with him. We don't need all these extra 'features' that almost nobody will use.

If you really need a new key, you can reinstall the app or wipe it's config and start again.
