### ISSUE TITLE
LED doesn't blink with ecryption enable

### ISSUE THREAD

**Issue by benjiprod** [SMSSecure/SMSSecure#261]
Smartphone : Google Nexus 5 & Sony Xperia Z2

Since 0.10.1 LED Notification doens'nt blink when I receive a secure SMS. (just 1 time and no more)
But when I disable encryption for the same contact, LED blinks correctly.

I try to modify LED colors, speed, name of contact but it didn't fix it.

Can you help me ?

**Comment by matthew8712** [comment]
I double that. After update from 0.10.1 LED flashes only once. LED notification works properly when conversation is not encrypted or application is locked.

Smartphone: Sony Xperia S

**Comment by remileduc** [comment]
I triple that! same bug with nexus 5 and CM 12.1, and with a Umi...

**Comment by remileduc** [comment]
just to be more precise, this bug still occurs on the last version (0.12.3)

**Comment by johanw666** [comment]
It is still a bug in 88c8ca0 (I'm running that build for over 2 weeks now).

**Comment by Darkitty** [comment]
Yes but when receive a MMS, the led blinks for me with the last version on F-Droid repo.

**Comment by benjiprod** [comment]
Work for me too with MMS only

**Comment by discworld** [comment]
88c8ca0 solves the problem on a Motorola Defy+. I will try to make a test on some other phones in the next days. Right now, I don't understand why the problem still occurs.

**Comment by discworld** [comment]
I've tested again on a Samsung Galaxy S5 just by reverting cf673cf and the blinking lights work for me.
johanw666, are you sure you had the right build when testing ?

**Comment by matlink** [comment]
I've got the same issue with version 0.13.0 , compilation ID 8ea8218 , nexus 5 CM 12.1

**Comment by henrykratom** [comment]
Same here under CM 12.1 CM13 with Nexus 6 & Moto-G

**Comment by henrykratom** [comment]
It is the same here under CM12.1 & CM13 with  Nexus 6 & MotoG

**Comment by henrykratom** [comment]
It is the same here under CM12.1 & CM13 with Nexus 6 & MotoG with  SMSSecure 13.0

**Comment by henrykratom** [comment]
It is the same here under CM12.1 & CM13  with Nexus 6 & MotoG with SMSSecure 0.13.0
And on some other phones running Stock Vanilla Android from 5.0 to 6.0.

So the bug is still persisting.

**Comment by discworld** [comment]
Perhaps someone can revert cf673cf and make a test on some other phones as well ? I made this test on 3 phones so far and the blinking lights are working afterwards.

**Comment by henrykratom** [comment]
Are we on the same page here?
The blinking does work, but only if  SMSSecure is locked with a passphrase, if you unlike it doesn't blink here after all.

Is it already in the repo of FDroid and by such i mean Version 0.13.0: https://github.com/SMSSecure/SMSSecure/commit/cf673cfc18d1f5502fcb75800e9bab121f03677c

i have further tried it on some Sony Devices of two Colleagues and it's the same.

**Comment by henrykratom** [comment]
Are we on the same page here?
The blinking does work, but only if  SMSSecure is locked with a passphrase, if you unlike it doesn't blink here after all.

Is it already in the repo of FDroid and by such i mean Version 0.13.0 Build: 8ea8218 : https://github.com/SMSSecure/SMSSecure/commit/cf673cfc18d1f5502fcb75800e9bab121f03677c

i have further tried it on some Sony Devices of two Colleagues and it's the same.

**Comment by henrykratom** [comment]
Are we on the same page here?
The blinking does work, but only if  SMSSecure is locked with a passphrase, if you unlike it doesn't blink here after all.

Is it already in the repo of FDroid and by such i mean Version 0.13.0 Build8ea8218: https://github.com/SMSSecure/SMSSecure/commit/cf673cfc18d1f5502fcb75800e9bab121f03677c

i have further tried it on some Sony Devices of two Colleagues and it's the same.

**Comment by henrykratom** [comment]
Are we on the same page here?
The blinking does work, but only if SMSSecure is locked with a passphrase, if it is unlocked it doesn't blink here after all.

Is it already in the repo of FDroid and by such i mean Version 0.13.0 Build8ea8218: cf673cf
Or am i missing out on an update that isn't yet synced into FDroid?
Can't check it right now

i have further tried it on some Sony Devices of two Colleagues and it's the same.

**Comment by discworld** [comment]
cf673cf is the patch that reverts 88c8ca0 (which was the fix meant to solve this issue). 88c8ca0 never made it into any build as far as I know. I've tested the Debug build on 3 different phones: reverting cf673cf (going back to 88c8ca0) fixed this issue.

**Comment by henrykratom** [comment]
Well then it is FDroid's fault?
I've asked around  and all my contacts report identical things to me about they having the newest 0.13.0 Build 8ea8218 out of Fdroid, i tried to contact somebody that get his updates through GooglePlay what Build-ID he has, but she hasn't contacted me back with the needed information.

Might there be a difference between the version provided in FDroid and Play Store?

**Comment by johanw666** [comment]
Ah, being locked seems to be the culprit, I admit I didn't test it while locked, but https://github.com/SMSSecure/SMSSecure/commit/a21886cf4a6125bf86b5a3dd278a22cc9a0ffec9 does blink when it is locked (Sony XPeria Z1 compact on 4.4.4).

**Comment by henrykratom** [comment]
@johanw666 
Yes exactly, and regarding the time of the mentioned commit this could be about right when i first starting seeing this issue.

I think it was one of the first 0.12.* Builds, or even right before Version >0.12.* was released.
The problem now is just that is seems like a waste of display-on time because atm there is no other possibility to check for incoming messages (while totally silent) other than turning on the Display or setting the Lock-Timeout to a minute and manually unlocking it.
Which is something you will not want to do, especially if you care about a strong password that isn't 1234.

**Comment by matlink** [comment]
For me, it blinks once before SMSSecure decrypts the message if the app is unlocked. Once decrypted, the message seems to be marked as read.

**Comment by matlink** [comment]
Great, thanks it works !
