### ISSUE TITLE
Notification counter

### ISSUE THREAD

**Issue by Woodzrul** [SMSSecure/SMSSecure#265]
Firstly I apologise for writing in the wrong section, I could not find a relevant forum. I am new to Android and learning how to decompile / compile code etc.

Within SecureSMS, when a message has been received a notification counter appears to the right (in the notification drawer). How do I remove this notification counter? Is there a particular line of code I need to remove or amend. I thought it might be to do with setSummaryText, but guessing I'm wrong.

This is a personal preference of mine and would be grateful for any help.

Please keep up the hard work.

Thank you

**Comment by pR0Ps** [comment]
The [Notification's number property](http://developer.android.com/reference/android/app/Notification.html#number) is set in [`SingleRecipientNotificationBuilder.java`](https://github.com/SMSSecure/SMSSecure/blob/848d2ab19a44c4ba7e042f6c194978566c3d7c31/src/org/smssecure/smssecure/notifications/SingleRecipientNotificationBuilder.java#L81) and [`MultipleRecipientNotificationBuilder.java`](https://github.com/SMSSecure/SMSSecure/blob/848d2ab19a44c4ba7e042f6c194978566c3d7c31/src/org/smssecure/smssecure/notifications/MultipleRecipientNotificationBuilder.java) by calling the [`setNumber` function](http://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setNumber%28int%29).

Removing the highlighted lines will stop the numbers from being displayed.
