### ISSUE TITLE
Backup to remote server

### ISSUE THREAD

**Issue by benoiton** [SMSSecure/SMSSecure#269]
It would be great be able to automatically backup SMS to remote server:
 * either to schedule data dump + push to remote server (DAV, sftp...)
 * or push received and sent SMS to an IMAP server (see https://github.com/jberkel/sms-backup-plus)

I use SMS Backup+, it just work, and I do not worry backup anymore.

**Comment by pR0Ps** [comment]
An integrated backup isn't something that's going to happen.

That being said, #145 seems like a good way to meet that demand halfway. It will allow messages of the user's choosing to be forwarded to the regular SMS database, allowing other 3rd party apps to take care of everything else without having to have a specialized app specific to SMSSecure.
