### ISSUE TITLE
Contact colours

### ISSUE THREAD

**Issue by Woodzrul** [SMSSecure/SMSSecure#270]
Not really an issue, but how easy would it be to make it so that the Contact avatar within SMSSecure (the coloured letter) be the same colour as it is in the native Contacts app? Just like Google Messenger.

Thought it might be a nice touch to keep things consistent.

Really like SMSSecure. :-)

**Comment by pR0Ps** [comment]
I just tried this. Every one of my contacts that I didn't have a picture for had a bubble color in Messenger that was different from the one that the contacts app assigned it.

I'm pretty sure that there's no way to check what color the default contacts app has given a contact and mimic it, although it would be nice.
