### ISSUE TITLE
better key management

### ISSUE THREAD

**Issue by imkarjala** [SMSSecure/SMSSecure#272]
The current mechanisms of SMS, with out-of-band verification, and QR codes work well enough for most people in most situations, but I think to really get network effect and wide spread proliferation of encryption I think there needs to be key server functionality implented at least over bluetooth.

I propose two different exchange procedures:
One:
Client sends server a numbered list of hashed phone numbers
For hashes that match the servers database, the server sends the client the corsponding public key and optionally a chain of custody

Two:
Server sends client vCards (w/ public key) of selected contacts

The first is very automated and the server(s) could listen on a broadcast or multicast ip address, the second would just be normal sharing of contacts with a little extra contact info and authentication between server and client.

If you have 100 people who all need each others keys, the first one would reduce the number of key exchanges from 5050 (99+98+97.....3+2+1) to 100 or less.

Maybe this should be a sister app and not part of the main app but I still think that this is a functionality that would aid proliferation.

**Comment by pR0Ps** [comment]
This is out of scope for this project.

Making verification easier is definitely something that should be done (see #44) but having to develop, deploy, harden, and maintain a key server is not something we have the resources to do.

Plus, in-person verification is pretty much impossible to compromise
