### ISSUE TITLE
Recipient received encrypted text

### ISSUE THREAD

**Issue by SethArchambault** [SMSSecure/SMSSecure#274]
A friend received a string of random characters instead of my messages. This was initially upon installing, she uninstalled it soon after. 

I'm down with encrypted messages, but I can't recommend this to my friends unless it works as well as their default messager

**Comment by pR0Ps** [comment]
SMSSecure will not send encrypted text unless the recipient has confirmed (via completing a key exchange) that they can receive it.

If the recipient has switched to a different SMS application that can no longer decrypt the encrypted messages, either you or the recipient must end the encrypted session from the lock icon on the top bar of the conversation view.

Even if SMSSecure is not set as the default SMS application for your recipient, it will still be able to see and decrypt messages, but the default SMS application will receive and display the encrypted data. This is probably what was happening in your case. To fix this, SMSSecure must be set as the default SMS application. This is a limitation of how receiving SMS works on Android.
