### ISSUE TITLE
Mixed SMS

### ISSUE THREAD

**Issue by matlink** [SMSSecure/SMSSecure#276]
Sometimes, I don't know why, I receive some SMS from a friend that are a mix of 2 SMSs: a beginning of the part he sent, and the end (from approx. the half) of a previously received SMS.
For example, I just received a SMS but the end half is from a SMS I received the oct 13th 21:46.

Is that an issue from SMSSecure that is scrambling SMSs or from my carrier ?

**Comment by pR0Ps** [comment]
Are these messaged in an encrypted conversation?

**Comment by matlink** [comment]
No

Le 11/11/2015 20:46, Carey Metcalfe a écrit :
>
> Are these messaged in an encrypted conversation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SMSSecure/SMSSecure/issues/276#issuecomment-155890709>.
>

-- 
Matlink - Sysadmin matlink.fr
Sortez couverts, chiffrez vos mails : https://café-vie-privée.fr/
XMPP/Jabber : matlink@matlink.fr
Clé publique PGP : 0x186BB3CA
Empreinte Off-the-record : 572174BF 6983EA74 91417CA7 705ED899 DE9D05B2

**Comment by pR0Ps** [comment]
If the conversation isn't encrypted, I would guess that It would be the fault of the carrier or the phone your contact is using, especially if it's sporadically happening with only that person.
