### ISSUE TITLE
New phone, SMS Secure wont receive 80% of sms messages.

### ISSUE THREAD

**Issue by 1337cookie** [SMSSecure/SMSSecure#277]
I recently change from a Huawei Y600-U20 using SMS Secure flawlessly, to a Huawei P8 Lite (ALE-L02) where I would only ever receive messages occasionally. 
When I would receive them, they would be on time and it was irrelevant whether they used SMS Secure or what network they are on. I got a new Sim card in case that was the issue. But it looks like SMS Secure on this phone seems to drop incoming messages. This phone does use a custom interface the Huawei EMUI. As soon as I switch back to the standard messaging app everything works normally but I wouldn't get the unseen messages, they were gone forever.

**Comment by Vitriia** [comment]
I have the same issue with my Asus Zenfone 2. I recieve 1 sms on 5 and that's when i'm lucky, Same for uncrypted import: 2000 sms and only 50 imported 
For the import i have trick: 
I have do a sms save with sms backup & restore and import them with the backup.

Sorry for my english
Asus Zenfone 2 ZE551ML android 5.0

**Comment by 1337cookie** [comment]
I found the solution for me.
This phone has a custom UI. There is an app called phone manager. In the settings for this app there is an option called "protected apps" and I had to turn it on there. 
It prevents all apps from running in the background unless allowed.

**Comment by StrikeOne** [comment]
I'm running CM11 ROM, almost bare bones system, no Gapps, no Google Play (no Google anything) and the only apps I have installed are Ghostery browser, Disconnect Search and SMSSecure. 

I am not receiving some SMS's - I posted in the thread #157 the log file shortly after missing one and further info I've posted can be read there...
