### ISSUE TITLE
Remove internet permission

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#28]
Since SMSSecure is aimed only at SMS/MMS, it does not need internet permission.

I finally got a build environment up, I made a test build of 0.3.3 without internet and it runs OK on my phones.

**Comment by BastienLQ** [comment]
It does, as MMS functionality needs data.

**Comment by johanw666** [comment]
Oops, sorry. I, tested it only with sms.

**Comment by BastienLQ** [comment]
Take a look at the source code of the stock SMS/MMS app (`com.android.mms`): you need INTERNET permission.
