### ISSUE TITLE
app crash on new message button

### ISSUE THREAD

**Issue by jadrienb** [SMSSecure/SMSSecure#286]
SMSSecure crash when i select new message button (message : "SMSSecure s'est arreté")

Version :0.12.3
ID compilation : 3b13ecb
Android 4.4.4 on Samsung SM-G901F

it's ok when I reply to a conversation, it crash only when new message button is selected.

I could send you a debug ?

**Comment by BastienLQ** [comment]
Yes, please, we need a debug log.

**Comment by jadrienb** [comment]
it say to  me : 
https://gist.github.com/389004d4580ceabc1567

**Comment by jadrienb** [comment]
I have uninstalled the app and reinstall it

then I restore my messages and the error is still here the app crash when I clic new message

**Comment by BastienLQ** [comment]
There is no crash in the log you reported. Did you send it immediately after a crash?

**Comment by jadrienb** [comment]
Yes I send it immediately after; maybe the app don't have time to make it?

I generate another one this morning here :
https://gist.github.com/9c68c7ac8b91061a7011

I could send a message to a new contact via the adressbook, it works.


2015-11-25 16:42 GMT+01:00 Bastien Le Querrec <notifications@github.com>:

**Comment by BastienLQ** [comment]
This one is OK.

**Comment by pR0Ps** [comment]
Fixed by c5d81b7f7181de1747f5706013035a78e9761c40
