### ISSUE TITLE
Fast scrollbar

### ISSUE THREAD

**Issue by Salamandar** [SMSSecure/SMSSecure#293]
It would be great to have a "fast scrollbar" as in the contacts app.

**Comment by pR0Ps** [comment]
This has already been implemented as part of #287 .

**Comment by Salamandar** [comment]
Doesnt seem to be updated on the store. Well, thanks :)  i'll wait for the update !

**Comment by pR0Ps** [comment]
That branch is currently going through testing, it should be released soon
