### ISSUE TITLE
Hide button to delete conversation in extra menu

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#299]
Guys, I just deleted a *very important* conversation due to me typing really fast. It happened multiple times to me before that the app menu was suddenly popping up, but I always could avoid accidentally deleting a convo. This time, it happened. Hoping that I can restore part of that conversation from my `TitaniumBackup`, but would you please hide that deletion button somewhere else, please? Thank you.

**Comment by pR0Ps** [comment]
The delete button is already under the "more options" menu. You said that menu is popping up without you touching it?

**Comment by SecUpwN** [comment]
>You said that menu is popping up without you touching it?

I am typing quickly, somehow I have managed to hit that button for "more options" in the past as well as now. It appears that this deletion button is just located where I would normaly type, now I have the huge problem of restoring my whole SMS database - I could *freak out* right now! :(

**Comment by johanw666** [comment]
Even if you have several messages in one backupand others in the current system, it is possible to export them to plaintext backup and edit the xml file manually to re-import only the missing articles. A bit of a puzzle but doable.

**Comment by SecUpwN** [comment]
>A bit of a puzzle but doable.

@johanw666, trhanks for trying to help, but it seems impossible since I've backed up the data via `TitaniumBackup`. That backup is several days old and when imprting it back into version `0.12.3`, SMSSecure crashes. Trying to apply the backup of `TitaniumBackup` onto the latest version does the same.

**Comment by pR0Ps** [comment]
Deleting a conversation takes 3 (mis)taps. Tap the menu button/icon, tap the delete conversation menu item, confirm the deletion by tapping the delete button on the alert that comes up.

Short of completely removing the ability to delete conversations form inside them (something I personally use a lot and don't think I'm the only one), I don't think there's any other way to reasonably make it harder to accidentally delete conversations.

**Comment by johanw666** [comment]
@SecUpwN: then it comes down to the hard work: restore the backup(s), store the tables somewhere else, install SMSSecure again and be creative with SQL INSERT INTO queries (look also for structure differences in the database between backups), and hope that works (it should if you restore your identity key). And you'll have to reset all secure sessions.

**Comment by SecUpwN** [comment]
@johanw666, thanks ffor being supportive. I managed to restore my backup after installing the latest `TitaniumBackup`, but I lost a few days. Sad thing. Now playing with moving on to `LibreSignal` or else.

**Comment by pR0Ps** [comment]
@SecUpwN: You may want to remove the menu item and build a custom version of SMSSecure for yourself. Building the app is pretty easy once your environment is set up.
