### ISSUE TITLE
Show emoji's in KitKat

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#30]
One of the irritations of TextSecure is that it won't show the emoji button in KitKat or higher, claiming it is on the keyboard. This is not true for some 3rd party keyboard, and TextSecure has an issue with the Samsung S5 default keyboard too. Solving it is done by removing or commenting out lines 743-745 in org/smssecure/smssecure/ConversationActivity.java: they read

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
  emojiToggle.setVisibility(View.GONE);
}

I realise this would diverge from TextSecure so I understand if you prefer not to do this.

**Comment by pR0Ps** [comment]
There are currently a bunch of issues and a pull request open against TextSecure to fix this issue. I'd rather wait until they sort it out and then just pull in their changes than implement it ourselves.

WhisperSystems/TextSecure/pull/2302

That being said, I recognize that emoji are important to people (for some reason) so feel free to re-open this after a few months if nothing has changed in the parent project.

**Comment by pR0Ps** [comment]
Fixed in d5aa70c
