### ISSUE TITLE
Regression in behavior

### ISSUE THREAD

**Issue by xavihernandez** [SMSSecure/SMSSecure#303]
Hi,

When you tap "New message" button, you have to look for, then select a contact. When you have selected wanted contact, conversation window comes, keyboard showing up, but focus is lost. Before last release, focus was on input textbox. Then you were able to write your message. Now, you have to tap on input textbox to give it focus, and then you can write. It's a little regression.

**Comment by pR0Ps** [comment]
Confirmed. Specifically:
- Searching using the number keyboard --> Keyboard switches to text but field isn't selected
- Searching using text keyboard --> Keyboard stays as text but field isn't selected
- Selecting a contact without searching --> Keyboard isn't shown, field isn't selected

**Comment by xavihernandez** [comment]
Thanks for clarification @pR0Ps!

**Comment by johanw666** [comment]
Perhaps solved by https://github.com/WhisperSystems/Signal-Android/commit/f3a4634d30e87175763695191a7f8348170ec064 ?

**Comment by xavihernandez** [comment]
Seems to @johanw666
