### ISSUE TITLE
SMS delivery reports always received

### ISSUE THREAD

**Issue by Tetsumaki** [SMSSecure/SMSSecure#304]
Hello,

All SMS are considered received with option SMS delivry reports but that is wrong, i tested with airplane mode and 2 phones.

Version : 0.13.0

**Comment by BastienLQ** [comment]
I can't reproduce. We didn't change anything in 0.13.0 related to delivery reports.

**Comment by Tonat-Systems** [comment]
Hey @Tetsumaki and @BastienLQ ,
some carriers already deliver delivery reports when your text reaches their network boundaries. So you may want to check with completely different carries.

**Comment by Tetsumaki** [comment]
**Tested from France with SMSSecure :**
Instant receive : Orange (send) to SOSH (airplane mode)
Instant receive : SOSH (send) to Orange (airplane mode)
Instant receive : Orange (send) to SFR (airplane mode)
Instant receive : Orange (send) to Bouygues (airplane mode)

**Tested from France with Signal :**
Not receive : Orange (send) to SOSH (airplane mode)
Not receive : SOSH (send) to Orange (airplane mode)
Not receive : Orange (send) to SFR (airplane mode)
Not receive : Orange (send) to Bouygues (airplane mode)

**Comment by nivram913** [comment]
I have the same issue with Silence 0.14.8
I receive delivery report whereas the recipient's phone is offline. It's because some network send delivery report with "Not delivered" message anyway. Silence doesn't differentiate delivery message.

**Comment by bastien30** [comment]
Hi,
Same issue with Silence 0.15.2 and 0.16.0-unstable from F-Droid.
@BLeQuerrec There is nothing you can do for that ?
Thanks

**Comment by Tetsumaki** [comment]
Reopen please ?

**Comment by rodeusdi** [comment]
With my Fairphone 2 I have the same issue. I receive a delivery report as soon as the sms was sent successfully, even if the recipient's device is turned off. So Silence does not differ between just sent and delivered.

I have tried the same with the app "SMS/MMS" by sending a sms to the same device: The sent sms has the state "sent" as long as the receipient's device is turned off and with turning it on the state changes to "delivered". (So it is not a problem of the carrier.)

I would be happy you would install the same behaviour in Silence.

Silence is the best sms app that I know, but to me it is decisive that it could differ if a sms is just sent or in fact delivered.

Thanks.
