### ISSUE TITLE
forwarding a SMS to a contact wich is not in the list of the contacts I already exchanged a SMS with

### ISSUE THREAD

**Issue by bikepunk** [SMSSecure/SMSSecure#307]
in version 0.13.0
forwarding a SMS to a contact wich is not in the list of the contacts I already exchanged a SMS with (ie. my contacts) doesn't work.
If I select a message, then forward message, then Share With "+" : any contact I select brings a new empty message window, without the desired message to forward.

**Comment by Tonat** [comment]
Sounds like it's related to https://github.com/WhisperSystems/Signal-Android/issues/4797

**Comment by johanw666** [comment]
Fixed in https://github.com/SMSSecure/SMSSecure/commit/de198e4ebd3188bfe9e2cef9dbfa2e5c3c7e7fc8

Tested with current master (https://github.com/SMSSecure/SMSSecure/commit/a21886cf4a6125bf86b5a3dd278a22cc9a0ffec9).
