### ISSUE TITLE
Wrongfully showing the Communication is encrypted when its not

### ISSUE THREAD

**Issue by henrykratom** [SMSSecure/SMSSecure#309]
Hello i noticed the following behavior:

If you send out a "Key" over the "Start secure foo.." Button and the person who gets the sms-message doesn't have SMSSecure and forwards you your previously send (key)message the communication is shown to be encrypted when it is clearly not as the user has no SMSSecure whatsoever.

I'm not sure if it is showing that the communication is encrypted when it is clearly not or if it is sending out messages to Person-X which are encrypted with your own public key(???)

Even if it would be the latter SMSSecure should notice that the key is identical to the previously send out and never visually show (Closed Lock Icon) that the communication is encrypted and functional when it is not.

I was able to replicate this error on the following Systems:

CM11 with  SMSSecure Version 12.1 12.3 13.0
CM12.1 with  SMSSecure Version 12.1 12.3 13.0
CM13 with  SMSSecure Version 12.1 12.3 13.0

Stock Vanilla Android 5.0.1 with  SMSSecure Version 12.1 12.3 13.0
Stock Vanilla Android 5.1.1 with  SMSSecure Version 12.1 12.3 13.0
Stock Vanilla Android 6.0 with  SMSSecure Version 12.1 12.3 13.0

The only possibility to disable this is to manually stop the "secure" communication.

 Greetings, Henry K.

**Comment by pR0Ps** [comment]
IIRC the messages would still be encrypted in this case, but only readable to yourself (so the lock icon is not totally invalid). See https://github.com/trevp/axolotl/wiki for details on the protocol SMSSecure uses.

We're using the same crypto technique as [Signal for Android](https://github.com/WhisperSystems/Signal-Android) and would like to keep it that way. It was developed by a respected cryptographer and has been proven to be secure.

Seeing as how someone forwarding you your own key exchange message back to you isn't a common occurrence (hopefully) and can be easily fixed if it happens accidentally (end the session), it's not worth modifying the key exchange code and inadvertently creating a vulnerability in it.
