### ISSUE TITLE
I get the SAME Message to BOTH the SMSSecure App AND the standard Android SMS Message App - HELP !!

### ISSUE THREAD

**Issue by mtzrrxza** [SMSSecure/SMSSecure#310]
When another SMSSecure User sends me a SMSSecure SMS Message

** I get the SAME Message to BOTH the SMSSecure App AND the standard Android SMS Message App - HELP !! **

How do I have Encrypted SMS Messages go to SMSSecure App ONLY
AND
the 'Normal' SMS Messages going to the standard Android SMS Message APP ????

It was all working FINE when I was using Android 4.2
** Now that I am using Android 5.0 I get the above issue !!!!

Help !!!!

**Comment by johanw666** [comment]
Which phone and which ROM? In Android 4.4 or later, all apps that register themselves as sms handlers get to see all incomming sms messages. Wether they do anything with them is up to the app. This gave issues in the past with TextSecure and SMSSecure on the same device too, where TextSecure gave warnings about outdated protocols when receiving an encrypted sms message.

If the default sms app always processes all incomming sms messages, wether it is set as the default app or not, there is nothing SMSSecure can do to prevent that.

**Comment by mtzrrxza** [comment]
>>Which phone and which ROM?

Samsung Galaxy S4 - Android 5.0 (stock ROM)

So is there nothing I can do to have it working as before when it was on Android 4.2 (Stock ROM) ??

**Comment by pR0Ps** [comment]
@mtzrrxza If you set SMSSecure as the default SMS app, then other applications won't receive the messages at all. If you set another app as the default SMS app, SMSSecure can still see, decode, and display encrypted messages, but whatever app you have set as the default SMS app will see everything, including encrypted messages.

Unfortunately, as of Android 4.4, what you want is no longer possible. You'll have to choose between using SMSSecure as your primary messenger (for encrypted and non-encrypted SMS) or have SMSSecure only see encrypted messages but have your other SMS app see everything (including encrypted messages).

**Comment by mtzrrxza** [comment]
>>pR0Ps
>>Unfortunately, as of Android 4.4, what you want is no longer possible.

Hi pROPS,

1) Does that mean I need to downgrade from Android 5.0 to Android 4.4 to get the functionality back ??
OR does that mean I need to downgrade from Android 5.0 to Android 4.3 to get the functionality back ??

2) Can I put in a feature request to have this fixed for those users on Android 5.X ??

Thanks

**Comment by pR0Ps** [comment]
This cannot be done in the app, it's at the OS level.

You would need Android 4.3 to have the same functionality. However, I would not recommend downgrading for security reasons.

**Comment by mtzrrxza** [comment]
>> pR0Ps commented
>>
>>This cannot be done in the app, it's at the OS level.
>>

Is there a 'patch' out there that fixes this at the OS level ?
