### ISSUE TITLE
IPhone App

### ISSUE THREAD

**Issue by zero77** [SMSSecure/SMSSecure#316]
This is a really great app and I have been looking for something like this for a while. Although half the people I know use IPhone and it doesn’t seem to be on their app store so are you planning to release this app on IPhone as well if so when do you plan to.

**Comment by pR0Ps** [comment]
iOS doesn't allow the sending/receiving of SMS by third-party apps - users can only use the built in app. This makes porting SMSSecure to iOS impossible at the moment.

However, you should look into Signal (the upstream project) it works across multiple platforms since it uses data to communicate.
