### ISSUE TITLE
Build fails in 0.13.1

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#322]
Android Studio reports errors in the Portugese translation file (pt\strings.xml):
```text
Error:(2) Apostrophe not preceded by \ (in Exportar um ficheiro em texto simples. CompatÃ­vel com 'SMS Backup &amp Restore'.)
Error:(2) Apostrophe not preceded by \ (in Importar um ficheiro em texto simples. CompatÃ­vel com 'SMS Backup &amp Restore'.)
```
Escaping the ' fixes the build. I see this has deliberately been changed in the update language translations commit.

**Comment by pR0Ps** [comment]
Fixed by 775b16043d4

**Comment by johanw666** [comment]
Shouldn't this also get fixed in Transiflex? Otherwise the problem returns each time when translations are updated.

**Comment by pR0Ps** [comment]
I've updated the strings in Transifex
