### ISSUE TITLE
Aldoni Esperantan tradukon

### ISSUE THREAD

**Issue by verdulo** [SMSSecure/SMSSecure#329]
Please add Esperanto translation to the program, it's finished in 81%. I have a question, some phrases (strings/12, strings/142...) are separated by new lines, should I add new lines to translation too, or the app will automatically wrap them according to the size of the phone-screen?

**Comment by pR0Ps** [comment]
If the newlines look like they separate paragraphs, put them in, otherwise you can leave them out.
