### ISSUE TITLE
Configuration with name 'default' not found.  Consult IDE log for more details

### ISSUE THREAD

**Issue by maxfiresolutions** [SMSSecure/SMSSecure#331]
Hi,

I am using Android Studio for building the latest Master copy of the project but on 2 PCs i get the same gradle sync error as given above. I have successfully compiled the Signal-Android version but i am not sure whats the issue in this. Please guide thanking in advance.

**Comment by pR0Ps** [comment]
This usually happens when the submodules haven't been checked out with the project. Make sure to follow the directions in [BUILDING.md](https://github.com/SMSSecure/SMSSecure/blob/master/BUILDING.md).
