### ISSUE TITLE
"Random" crashes

### ISSUE THREAD

**Issue by maxauvy** [SMSSecure/SMSSecure#337]
Hi there,

since several days, I encounter quite numerous FCs , especially when opening a conversation through notifications, with SMSSecure "unlocked". I can't give you some precise steps to reproduce it, as it seems to be quite random.

It may happen several times a day...

Here's the log I recorded:
https://gist.github.com/anonymous/4e0f883e1ba453e77558

If you need something else, just ask :)

I'm using SMSSecure 0.13.1 (from F-Droid) on my LG G4 (h815) running CyanogenMod 13 (Android 6.0.1).

**Comment by BastienLQ** [comment]
There is no SMSSecure crash in the provided log. The only interesting line is [L193](https://gist.github.com/anonymous/4e0f883e1ba453e77558#file-cat-log-L193) which seems to be an LG issue.
Are you sure this debug log was generated right after a crash?

**Comment by maxauvy** [comment]
Right after the crash, I can't reopen SMSSecure, it stays on a blank screen. I have to soft reboot my device...

**Comment by BastienLQ** [comment]
It confirms that this is an OS-related bug. Did you recently upgrade your OS or firmware? Can you try to get a debug log directly using adb (see [`CONTRIBUTING.md`](https://github.com/SMSSecure/SMSSecure/blob/master/CONTRIBUTING.md))?
