### ISSUE TITLE
No notification when activity runs in background 

### ISSUE THREAD

**Issue by lmorel3** [SMSSecure/SMSSecure#338]
Even with the option checked, notifications never appear when, in a conversation, I exit the app by pressing the "home button".

**Comment by BastienLQ** [comment]
Do you receive messages properly?

**Comment by lmorel3** [comment]
Yes sure.

Phone: Nexus 5 w/ Android 6.0.1 (stock)

**Comment by BastienLQ** [comment]
Can you grab a bug when this bug occurs?

**Comment by lmorel3** [comment]
There's no error... 
The notification dosen't appear, that's all. 
So, I can't see the new messages of this conversation until I go back in.

**Comment by BastienLQ** [comment]
Yes, but you can generate a debug log (in settings) when you receive a message without notification.
Does it occur with secure, unsecure, or both?

**Comment by lmorel3** [comment]
It seems to work now, thanks for the support.

Laurent
