### ISSUE TITLE
automatically encrypt/decrypt outgoing and incoming

### ISSUE THREAD

**Issue by mm232** [SMSSecure/SMSSecure#341]
could you add a feature that could intercept outgoing and incoming SMS and automatically encrypt and decryp them? I know it's possible to do this because there used to be a Google Voice app that would automatically reroute through Google Voice

**Comment by BastienLQ** [comment]
If you send a message using SMSSecure to a recipient that uses SMSSecure too, messages will be encrypted.
Additionally, you can encrypt the local SMSSecure database if you set up the passphrase protection.
