### ISSUE TITLE
ability to encrypt while still using default sms app

### ISSUE THREAD

**Issue by mm232** [SMSSecure/SMSSecure#342]
Can u add a feature so smssecure can encrypt messages I send using the default SMS app? 

A feature like that would be popular because its hard to get ppl to download and use special apps just to chat. But if they could still use they're favorite SMS app they might be more willing

**Comment by pR0Ps** [comment]
You're talking about basically what CyanogenMod did with WhisperPush (FYI
they're shutting it down:
http://www.cyanogenmod.org/blog/whisperpush-end-of-life )

Did some research, this seems to be impossible as a normal app. The Google
Voice integration was probably baked into the OS or as a system app, giving
it more permissions than a normal app would have.

Even if it was possible, there are concerns with this transparent SMS
encryption. A lot of details would be abstracted, but the abstraction would
"leak". Regular SMS apps have no way of showing the user anything but SMS
messages. This is problematic in cases where user input is needed (dealing
with key mismatches, verifying that you want to start a secure session).

Also problematic is showing that the session is encrypted. If all you see
is messages from your friend, how would know if they were sent (encrypted)
from him, or if someone else is spoofing his number and sending unencrypted
messages. In SMSSecure we have icons and warning messages to show this - a
normal SMS app can't provide that.

The more "magic" and transparent we can make this the better, but there are
still things that require UI components that wouldn't be present in other
SMS apps.

**Comment by BastienLQ** [comment]
Additionally, SMSSecure aims to be a perfect SMS/MMS app replacement: this way, people will be happy to switch to it.
That's why any feedback is appreciated. I'm closing this issue, but feel free to open another one if you have UI suggestions.

**Comment by mm232** [comment]
An app that decrypts incoming SMS is

https://play.google.com/store/apps/details?id=com.woodkick.pgpsms&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dpgp+sms&pcampaignid=APPU_1_gquzVomgBsWq-AGapo2gDA

And the google voice is 

http://m.darkpsytrancer.store.aptoide.com/app/market/com.mdrtools.apps.gvintegration/25/2585835/Google+Voice+SMS+Integration

**Comment by pR0Ps** [comment]
Incoming is easy - we do that already.

The GV app requires root to work which is not something we're going to
support. It also looks really old and isn't listed anywhere other than that
page which is a good sign that it doesn't work anymore (or never did).

Also, I hope you didn't actually install a sketchy apk which:
 - Requires root
 - Doesn't provide source code
 - Has a signature mismatch
 - Is provided via a 3rd party app store
 - Was uploaded by a Russian that goes by "blackmark"

Good way to get your device owned.

**Comment by mm232** [comment]
I used it back when it was on the play store. It didn't require root. I assume it reciieved a message thru gv, , deleted it and inserted the message into the SMS app.  And did the reverse for sending. Using permissions (read SMS, send SMS, edit SMS). Pgp SMS receives the encrypted SMS decrypts it and inserts it.

**Comment by mm232** [comment]
(Read sent SMS, stop sent SMS, send SMS thru gv, or encrypt, then insert as sent SMS)
