### ISSUE TITLE
I can't receive MMS - Je n'arrive pas à recevoir les MMS

### ISSUE THREAD

**Issue by Rom-nain** [SMSSecure/SMSSecure#360]
Bonjour,

Je rencontre un problème depuis quelques semaines avec SMSSecure :

Lorsqu'une personne m'envoie un MMS, il m'est impossible de le lire.

Voici ce qui s'affiche :
"
Message multimédia
Appuyer et configurer les paramètres MMS pour continuer le téléchargement
"

Et quand je clique, voici ce qui s'affiche :
"
Configure MMS Settings
SMSSecure nécessite les paramètres MMS pour envoyer [...] Vous n'aurez besoin de faire cela qu'une seule fois.
"

Je fais OK, et j'arrive dans les "Paramètres MMS manuels", avec les champs suivants :
- URL MMSC
- Serveur proxy MMS
- Port du proxy MMS
- Nom d'utilisateur MMS
- Mot de passe MMSC
- Agent utilisateur MMS

Avant d'avoir ce problème, je n'avais pas modifié ces paramètres (ni les APN dans les paramètres d'Android)

Avez-vous une solution ?
Merci,

Voici les informations concernant mon téléphone :
- OS : CyanogeMod (rooté)
- Android : 2.3.7
- Réseau : Free (France)
- SMSSecure : 0.13.2

**Comment by nagromdt** [comment]
https://mobile.free.fr/assistance/64.html

Ca a résolu le soucis chez moi.

**Comment by Rom-nain** [comment]
Bonjour,
Ça fonctionne parfaitement !
Merci beaucoup
