### ISSUE TITLE
SMSSecure's github repo should no longer be a fork of TextSecure/Signal-Android

### ISSUE THREAD

**Issue by eighthave** [SMSSecure/SMSSecure#362]
Since the development has diverged for SMSSecure and TextSecure/Signal-Android, this git repo should no longer be considered a fork of TextSecure/Signal-Android as far as github.com is concerned.  It makes it hard to submit pull requests against the two apps separately.  As far as I can tell, a github repo can be converted to "normal mode" by asking github.com support:

https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by BastienLQ** [comment]
Done. I'm waiting for an answer.

**Comment by BastienLQ** [comment]
Done.
