### ISSUE TITLE
Remove "Invite to SMSSecure" nag?

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#363]
Added in 0140137d9f8cebb3d622d20154311e741fc749c8

Having a dialog that needs to be dismissed for every individual contact is pretty annoying, even if it does only show once. If people want to invite contacts to use the app, there's an option already in the overflow menu.

In my experience, asking a contact to use an app is something that's motivated by external factors (talking with them in person for example), not something that the user just needs a push to do.

The majority of the cases are covered by:
 - Discovery (app sees whitespace tag, asks to set up an encrypted session)
 - Helping a contact set up the app in-person (get them to install the app, immediately set up an encrypted session)
 - External motivation (SMSSecure comes up in conversation, user sends contact an SMS/uses the invite menu item)

Should this be pulled out before the next release?

**Comment by BastienLQ** [comment]
My idea is to allow the user to globally disable that notification in
settings.

**Comment by vdveer** [comment]
Globally disable preference would be my choice too, as well as adding a button 'never' to the thread notice.

**Comment by pR0Ps** [comment]
I would prefer not having it at all.

When presented by a text that nags me to invite someone to do something, my
immediate reaction is to close it and try to turn it off. I feel like this
is most people. Why would we bother having and maintaining another option
that almost everyone is going to have to turn off to get their desired
behavior?

I would think that almost nobody world like having a pop-up every time they
message a new person reminding them to tell them about an app. I think most
would call it "spam".

We got complaints about the "Rate me" pop-up and that was only shown 1 time
ever and had a clear way to disable it. I don't think this is going to help
adoption, I think it's going to bug people and cause them to think about
looking for another messenger.
