### ISSUE TITLE
MMS not working: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by MatejKovacic** [SMSSecure/SMSSecure#367]
Hi,

I got MMS and SMS Secure is unable to display it. It says I need to enter MMS settings manually.

My operator is Simobil, settings should be:
MMS server: 80.95.224.46
Port: 9201
username: simobil
pasword: internet

However, after I enter the data, MMS still cannot be received...

**Comment by janecz-n** [comment]
Same here, in France ;)

Can you tell me your version number of SmsSecure ?

I'm on V0.13.2 (PlayStore), Android V4.4.2

I will try to take a look. I think the "bug" could come from the last update ("0.13.2") with the last update of APN Database.

**Comment by FsShigeki** [comment]
I got the same problem in Poland in Play operator.
    punkt dostępu (apn): mms
    username: empty
    hasło: empty
    MMSC: http://mmsc.play.pl/mms/wapenc
    proxy: empty
    port: empty

I have correct apn in android 6 and still send/recive mms error.

Version 0.13.2 ID 5ddd099 from F-Droid

**Comment by BastienLQ** [comment]
@MatejKovacic @janecz-n @FsShigeki Can you attach a debug log taken right after an error?

**Comment by FsShigeki** [comment]
Logs : http://pastebin.com/7MBrVJqx

**Comment by BastienLQ** [comment]
Same here, with a mobile without Xposed framework. https://gist.github.com/anonymous/3ee91a387afb483173375be832646d34
