### ISSUE TITLE
Feature: Fallback to Android default sim setting for messaging on absent preference in DB

### ISSUE THREAD

**Issue by vdveer** [SMSSecure/SMSSecure#371]
This feature request is about code currently only available in master-branch, not in a specific release. 

When I open a new conversation with a recipient for the first time, it always selects the first sim when there is no preference in DB. As I always use second sim for messaging I have set this as default in Android. Would be nice to offer this to users of SMSsecure as well.

**Comment by johanw666** [comment]
Dual SIM support for Android >= 6 is in the current master. It will be in the next release.

**Comment by vdveer** [comment]
I have been using the master code on my phone since a couple of weeks and this is a request/fix for that code. Should have noted that in the details.

Dual sim support will be available for >=5.1 by the way and it works pretty well!
