### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by stan2100** [SMSSecure/SMSSecure#374]
I have imported the project to android studio. I get the message (see above). 
Can someone help me how to execute the command "git submodule init && git submodule update"? I don't know where to put this lines.
Thank you!
...I use Android Studio with Windows 7 with Git-2.8.0-64-bit.exe

**Comment by pR0Ps** [comment]
You need to open a terminal window, cd to the project directory, then run
those commands.

**Comment by stan2100** [comment]
Thank you very much :-)
But I'm still not able to run the project and install the apk. But mybe I'll figure it out some day.
