### ISSUE TITLE
[suggestion] Export (plaintext) backup to location readable over MTP

### ISSUE THREAD

**Issue by axelsimon** [SMSSecure/SMSSecure#375]
Hi,

Currently, the export plaintext backup option creates a file at:
/storage/emulated/0/SMSSecurePlaintextBackup.xml

This path is not accessible via MTP, which is Android's current default way of mounting and accessing a phone's storage space.

I suggest exporting by default to:
/storage/emulated/0/android/data/org.smssecure.smssecure/files/

I'm aware it's less obvious to find than at the root of the SD card, but if the files at the root of the SD card aren't visible over MTP, this is the next most logical space to find them.
Or /sdcard/whatever/SMSSecure/ (which isn't currently created, I think)

Thanks for considering this.

axel

**Comment by BastienLQ** [comment]
Hi @axelsimon,

What Android version do you have? Do you have an SD card? I don't really understand your issue because `/storage/emulated/0/` **and** `/sdcard/` are available through MTP, at least in CM 12/13.

**Comment by axelsimon** [comment]
Hi Bastien,

This is stock Android 6.0 on a Moto X (2nd gen). There is no SD card.

But this issue might be moot: I just tried it again, this time
SMSSecurePlaintextBackup.xml appears at the root of the “internal
storage” mounted via MTP. Strange, as last time the file was nowhere to
be seen and I was under the impression that MTP didn't show the files at
the root of the SD card (or internal storage).

Not sure this issue still makes sense then. Though one could argue
dumping stuff at the root of the SD card partition isn't the cleanest,
but it's also the easiest way to ensure people will find it easily…
Please feel free to close this issue :)

thanks

axel

**Comment by BastienLQ** [comment]
See #195 for options.
