### ISSUE TITLE
Unable to send text message

### ISSUE THREAD

**Issue by Danisheikh11** [SMSSecure/SMSSecure#379]
Hey. I recently download the app from playstore and tried it by sending a normal text to my brother's smartphone. But it was not delivered instead it was keep on saying "sending" in details. I waited for it for almost a day but it was giving the same status.

**Comment by BastienLQ** [comment]
Do you have a multi-SIM phone? We will release the next version with multi-SIM support in the next days.

**Comment by Danisheikh11** [comment]
Yes. I have dual sim phone. And thank you. I'll be waiting for it.
