### ISSUE TITLE
Gradle build fails with Android Studio

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#49]
I used to be able to extract the Git project manualy, open it by Android Studio and buid it on windows 7 with the latest JDK. 1.7. However, this fails now. The method described in BUILDING.md gives the same error:

Error:(124, 0) CreateProcess error=2, The system cannot find the file specified

This is the line
buildConfigField "String", "BUILD_GIT_COMMIT", "\"" + 'git rev-parse --short HEAD'.execute().text.trim() + "\""

When I replace "git" with the full path to it I get further (although adding this directory to the path didn't help and Android Studio knows where my git is installed, and says it's OK). However, then I get another error:

Error:Unable to find module with Gradle path ':libs:org.w3c.dom'.

To solve this one, I had to run the batch file gradlew.bat in the libs/org.w3c.dom directory.

My knowledge of these systems is insufficient to write a patch but I hope the information is sufficient for someone more familiar with Gradle to do so.

**Comment by pR0Ps** [comment]
I've submitted a patch for the first issue. I'm not sure what the second issue is about, but it seems like the submodule wasn't cloned properly or something.

I'll close this issue based on the first problem, but feel free to open a new one about the second issue if you can reliably reproduce it after a clean clone.

**Comment by BastienLQ** [comment]
Yes, submodules aren't included in the GitHub zip. So you need to get them separately before running gradle/gradlew. That should fix the second part of your issue. For the first part of your issue, #50 is a workaround if git is not installed. If git is installed but cannot be found, check the PATH environment variable (on *nix, but I think on Windows too).

**Comment by johanw666** [comment]
I cloned the latest source from Github with Android Studio and opened it. Now I get an error whenmopening the file: "Configuration with name 'default' not found." When I click that away and import the project I get the same error. I have not yet been able to solve this.

**Comment by BastienLQ** [comment]
See https://github.com/SMSSecure/SMSSecure/blob/master/BUILDING.md: you need to update libs. As you do not use git to obtain SMSSecure, you must download by hand submodules in `libs/*`.

**Comment by johanw666** [comment]
OK, when I download the project with

git clone --recursive https://github.com/SMSSecure/SMSSecure.git

and open it I get a warning I have to add vcs roots. When I do that (in File - Settings - Version Control, I had to scroll the red lines to the right to see a clickable link (add") the project builds clean. It even does not give errors anymore about missing translations for Nepalese and a few other languages.
