### ISSUE TITLE
Adapt colors to the new icon

### ISSUE THREAD

**Issue by BastienLQ** [SMSSecure/SMSSecure#51]

**Comment by johanw666** [comment]
This affects at least:

/res/drawable/info_round.xml: field solid android:color
/res/values/colors.xml: fields textsecure_primary and conversation_item_sent_push_background_light

(I just searched for the standard blue color 2090ea as used in TextSecure).

**Comment by landry314** [comment]
maybe this should be a different issue but what about making the flashing light notification purple too? it isnt an option right now. if the light CAN turn that color i would love to have the option to make it purple to match the new purple theme that seems to be developing.

**Comment by c33s** [comment]
please make it customizeable or user configurabe. i personally want that smssecure looks like textsecure and i don't like purple.
please keep the themes, or make them selectable.

**Comment by johanw666** [comment]
Perhaps expanding the number of themes would be the easiest way to make those colors configurable. One could for example choose between light blue (TextSecure), dark blue (TextSecure), light purple, light green, dark purple, dark green, etc. etc.

**Comment by pR0Ps** [comment]
Will be fixed by #65
