### ISSUE TITLE
New group causes app to close

### ISSUE THREAD

**Issue by D0L0S** [SMSSecure/SMSSecure#55]
Device: Nexus 5
Version: 5.0.1

Description: 
The New group page noes not allow you to add a contact to the group you are attempting to create. And when you press enter on the new group screen the app closes.

Steps:
Click New group
Attempt to enter a name
click enter
app closes

**Comment by BastienLQ** [comment]
I can't reproduce it. Which build ID do you have?

**Comment by D0L0S** [comment]
Version: 0.4.2
Build ID: 842b281

**Comment by BastienLQ** [comment]
Weird... Can you post a log?

**Comment by D0L0S** [comment]
OK, so this was part bug and part user error. 
Bug:
The app will crash if you click the + button without typing a name. 
User Error:
The keyboard is presented however the add member field is not selected.

**Comment by pR0Ps** [comment]
I can reproduce this and I know why it's happening. I'll take this.
