### ISSUE TITLE
webpage smssecure.org redirects to nuolez.io

### ISSUE THREAD

**Issue by c33s** [SMSSecure/SMSSecure#62]
the webpage http://www.smssecure.org/ redirects to https://nuolez.io/
i think this is not intended, is it?

**Comment by pR0Ps** [comment]
Correct, @BastienLQ?

**Comment by BastienLQ** [comment]
What what what? All is good for me... Did you clean your browser cache?

**Comment by Dostoi** [comment]
I'm having the same issue

**Comment by c33s** [comment]
the right page showed up correctly one or a few days ago. today is the first time the forward is there.

i just rechecked it again, now the correct page shows up

**Comment by BastienLQ** [comment]
In fact, I didn't configure *www.*, only *smssecure.org*. Fixed, now.

**Comment by c33s** [comment]
fyi: the www. url is the url listed on f-droid
