### ISSUE TITLE
Message shown as sent by me instead of the other person

### ISSUE THREAD

**Issue by Dostoi** [SMSSecure/SMSSecure#63]
I received a sms just before sending a picture (like 2 sec before) and when I sent the picture to the person sending me a sms, his sms was shown as if I was the one sending it.
And when he send me another sms, his bugged sms turn back to be shown as his sms.

Don't know if I'm clear enought ^^

And after that, when I sent another message to the same person, the last message received by me bugged to and was shown as if I was the one who sent it. Again receiving a sms from that person fixed it.

With smssecure 0.5.1 from f-droid on a wiko cink peax2 with android 4.1.2

**Comment by pR0Ps** [comment]
Sorry, I have no idea what's going on here. Can you reproduce it? If so, could you capture a log of the problem happening?

**Comment by Dostoi** [comment]
Never managed to reproduce it, so I'm closing the issue
