### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by emersion** [SMSSecure/SMSSecure#65]
It would be cool to be able to select custom messages colors.

**Comment by BastienLQ** [comment]
I agree. As some people doesn't like the blue and may not like the future purple from the icon, we could allow the user to choose a custom color.

Related to #51.

**Comment by c33s** [comment]
with the last update 0.10.1 this feature is really important.
please add more themes and more visual customization. 
i am wishing back the simple dark theme.
settings for custom themes and "color each contact seperatly",... would be a good addition.

**Comment by emersion** [comment]
Not relevant anymore, thanks!
