### ISSUE TITLE
Website crashes Palemoon browser

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#71]
The site http://smssecure.org somehow manages to make the Palemoon browser consume huge amounts of memory. After the single tab (smssecure.org was the only site open) took 3,5 GB the browser became unresponsive and I had to force close it. In IE on the same machine it worked OK.

System: windows 7 64 bit with 6GB memory, Palemoon 25.3.1, Adblock and Ghostery installed (but they didn't report anything).

**Comment by BastienLQ** [comment]
I don't have neither Palemoon nor Windows, so I need your help to fix that. Can you send a mail to support@smssecure.org?

**Comment by johanw666** [comment]
Sorry, I was quite busy. I did narrow down the culprit: if I leave out https://buttons.github.io/buttons.js I don't have the memory exploding. Studying the script though didn't reveal much to me yet.

**Comment by pR0Ps** [comment]
A separate issue should be created on https://github.com/SMSSecure/smssecure.org to track this.

**Comment by johanw666** [comment]
The new version without the buttons.js works fine in Palemoon. On https://github.com/SMSSecure/smssecure.org I don't see the issue button so I can't do it there.

**Comment by BastienLQ** [comment]
I disabled issues in other projects to have all issues centralized.
