### ISSUE TITLE
Make password screen theme sensitive

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#73]
Good evening lovely ladies! One thing that has always bugged me when using TextSecure, was that the main password screen is not changing its background to the theme (dark/light) I have set in the preferences. Sometimes I get an SMS in the middle of the night - and even though I have set a dark theme, the main screen always makes my eyes hate me for looking at it. Please change that. Thanks!

**Comment by pR0Ps** [comment]
There is a pull request in the upstream project to make this happen. I'll close this once we pull it in.

**Comment by SecUpwN** [comment]
Thank you for doing so, @pR0Ps. May I ask what `upstream` means? You're adding it to TextSecure?

**Comment by pR0Ps** [comment]
Yes, upstream is TextSecure. It's an improvement that applies to both so TextSecure should benefit as well. Plus, TextSecure has an open pull request to add this in already. We'll just pull it in when it's added upstream.

**Comment by nwdev** [comment]
Duplicate. https://github.com/WhisperSystems/TextSecure/issues/2296

**Comment by SecUpwN** [comment]
@pR0Ps, thank you so much for finally implementing this. Works beautifully! :smile_cat:
