### ISSUE TITLE
SMS delivery reports

### ISSUE THREAD

**Issue by BoyanStoyanovich** [SMSSecure/SMSSecure#75]
This is a regular and important SMS feature, so it should be in the app.

**Comment by pR0Ps** [comment]
Settings -> SMS and MMS -> SMS delivery reports.

Is something not working with it?

**Comment by BoyanStoyanovich** [comment]
I was blind.. and you opened my eyes in this late hours :)

Thank you and sorry for bugging without a reason...

Ticket closed.
