### ISSUE TITLE
Change Wording of "Receive all SMS" Setting to Make it Clearer and Change Default State

### ISSUE THREAD

**Issue by landry314** [SMSSecure/SMSSecure#78]
Currently the "Receive all SMS" setting along with its sister setting "Receive all MMS" is not clearly written to describe what it does and its default state can cause havoc on an unexpecting user's system so it should be changed to disabled.

1) I would add the following 3 words to the end, "Use for viewing and storing all incoming text messages <i>including unencrypted ones</i>" to make it clearer that this is what <i>all</i> means in this case. I would also delete the word "SMSSecure" because it is obvious and it takes up screen space.

EDIT: after testing this second suggestion (#2) below I see SMSSecure is letting messages through so I was wrong. I explain more in my comment below. I didn't delete it because I think it maybe should be preventing them from reaching the regular app but it isn't working correctly?

2) This is really important. With this setting enabled, SMSSecure is not only viewing and storing all incoming messages, it is also <i>not allowing other apps to touch them</i> meaning your regular text app will no longer see any messages. Someone installing this app the first time might not understand this and be very confused why they cant see any messages in their regular text app. The description should explain this somehow. I suggest:

"Use for storing all incoming text messages including unencrypted ones and prevent other text apps from handing"

"Use for storing encrypted and unencrypted text messages and prevent other apps access to incoming messages"

I know this is getting kind of long. Anyone have a more verbose way to explain this clearly?

3) Don't make this setting on by default. A normal user might install this app to talk to his geeky android friend and then all of a sudden his text apps stop working! A user should have to turn this on intentionally since it is a powerful setting which changes functionality in other parts of his system. He might have never even seen this setting yet and can't figure out why he can't get texts.

**Comment by landry314** [comment]
oh wait a second, i just tested this. this is not like textsecure? this setting doesnt put all messages in the app's own database? that was a good feature of textsecure, that i could put all messages, even unencrypted ones, into textsecure and then not have them go into the standard database and hence be protected if someone stole my phone.

if that is not suppose to be a feature of smssecure, then nevermind #2 above... i still think it should not be on by default because it would clutter up my textsecure and i might not know i can stop it from doing that. why have 2 copies of the same message in different apps, anyway? a user would have a worse experience of smssecure if they go into the app to find an encrypted conversation and there are all these unencrypted ones in the way. but there is less reason to make it off by default if you cant prevent other apps from getting text messages and using the standard android message database.

**Comment by pR0Ps** [comment]
We use the same defaults and strings as TextSecure does. It behaves in exactly the same way.
