### ISSUE TITLE
MMS Error

### ISSUE THREAD

**Issue by lalapt** [SMSSecure/SMSSecure#85]
Hi, right now i can't receive or send MMS. Was checking the APN db of these app and noted some discrepancies between what the network send me and what was on the database. I'm currently on Vodafone PT. I need to say that I can get MMS on the default app and in an earlier version of Textsecure (2.1.10)

APN: net2.vodafone.pt
Proxy: iproxy.vodafone.pt
Port: 80
Username: vodafone (not ok)
Password: vodafone (not ok)
Server: Not Set
MMSC: http://mms.vodafone.pt/servlets/mms (ok)
MMS Proxy: iproxy.vodafone.pt (ok)
MMS Port: 80 (ok)
MCC: 268 (ok)
MNC: 01 (ok)
Authentification type: PAP (not ok)
APN Type: default,supl,mms (ok)
APN Protocol: IPv4 (not ok)
APN roaming Protocol: IPv4 (not ok)
Bearer: unspecified (i think its ok)
MVNO type: none (ok)

The settings that have ok are according to the db, but the others don't exist or are wrong. 
You can also get the log here: https://gist.github.com/ab33452a0210fe76f9be

I really hope that someone can help me.

**Comment by Thunderpig72** [comment]
+1. I can't receive MMS, even though the settings are exactly like they should be.

I noticed the port was wrong, so I changed that. Still doesn't work though.

**Comment by hg8** [comment]
I have the same problem here. Can not send or receive MMS.
I can provide log if needed.
LG G3 : 5.0
Orange France

**Comment by maxauvy** [comment]
Same here. It *MIGHT* work, but it seems the God of Randomness is playing with my nerves. I can post a log, if needed. Just ask! :)

LG G3 (d855)
CyanogenMod 12.1 (Android 5.1.1)
Free Mobile (France)

**Comment by BastienLQ** [comment]
@maxauvy v0.8.0 introduces some changes in MMS reception, but keep in mind that Free Mobile in France have a poor MMS service.

@lalapt @Thunderpig72 @hg8 Do you still experience MMS issues?

**Comment by maxauvy** [comment]
@BastienLQ I know, but still, there's a margin between being unable to receive/send any MMS at all, and taking time to send one ;)
I'll keep you informed on the behaviour of v0.8.0 with MMS.

Newbie question: why does SMSSecure use a database with all MMS APNs instead of just using the one that is configured (system-wide) in the settings of the phone?

**Comment by BastienLQ** [comment]
@maxauvy The DB is used when system settings aren't available.

**Comment by hg8** [comment]
@BastienLQ 
Works great now with v0.8.0. Thanks for your work!
