### ISSUE TITLE
Multiple SIM/identity support?

### ISSUE THREAD

**Issue by drdaeman** [SMSSecure/SMSSecure#86]
Thanks for a great project! I'm curious what you stance on multi-SIM phone support is, as this is what matters to me. ;)

Regrettably, TextSecure held that since Android (as blessed by Google) didn't have an official API for this, they said they weren't going to support it. The situation had recently changed with 5.1 getting an official API, but TextSecure had dropped SMS either way.

I have a patch for old version of TextSecure that adds basic Samsung dual-SIM support (tested on my S4 mini), but before suggesting any code/patches I'm curious whenever this feature is desirable at all and if it is (hope it is!) - about the overall architectural vision on how it's best to implement everything.

The most important question is whenever every SIM should have its own independent identity (and, possibly, other state like conversation history), or they should be considered interchangeable transports and share the state. Or if there should be support for multiple identities, but they shouldn't be tied to particular SIM and can be switched freely. Or something else.

**Comment by pR0Ps** [comment]
I hadn't really given any thought about phones with multiple SIM cards. Since I don't have one, I never looked into it, but it seems like supporting that configuration would be a plus.

I'm not sure how it would be integrated though. How do normal SMS applications implement dual-sim phones? An option to switch numbers?

With that being said, I would resubmit your patch to the TextSecure project, making sure to let them know that there is now an API for it in 5.1. Even though they don't support encrypted SMS, they do support normal SMS. Now that Google has an actual API for this, I don't see any reason why they wouldn't want to add the feature in.

**Comment by drdaeman** [comment]
Thanks for the pointers. I've bumped the upstream issue on this.

As for how SMS apps handle multiple SIM:
- When a message is received, it's saved together wist slot and IMSI information, and a SIM card number is displayed in UI. Usually, it's just an icon with slot number, near other metadata (time, receipt confirmation icon). Sometimes (seen this on CyanogenMod), a short card name text is also added.
- As for sending, generally there are two approaches - either the app has multiple distinct buttons, or they allow to chose the outgoing card by some means, for example, with context menu or by long-tapping the send button. In simplest cases, the apps are multi-SIM-aware in sense that they display the identities but have a single "send" button and completely rely on system preferences to dispatch the message with correct card.

**Comment by Draky50110** [comment]
A little description with y own dual SIM phone.
I have a "Wiko" (French version for a chinese TCL smartphone, also sold as Micromax in India).

It runs Android 4.2.x and if you're on the phonepad screen or with any SMS app, if you dropdown the notification bar, you'll be able to choose : 
- SIM 1
- SIM 2
- Ask me everytime

If you enter an SMS conversation, it will automatically be assigned to the choice you made in the "general SMS view", SIM1 by default.
But in a conversation, you can of course change the SIM used.
In the conversation, each message will be shown with the SIM used, so you can have one conversation with one person... but with 2 SIMS, if you're a little... noobish :p !

Here is a screenshot found on the Internet, showing the notification down : http://images.frandroid.com/wp-content/uploads/2012/10/wiko-cink-slim-dual-sim1.png
You can see 3 choices : 
- Orange
- SFR
- Always ask

It is implemented within the OS I think, as it is the same "notification choice screen" for every "app" : contact (you can assign a contact to a SIM), SMS, phonepad, and so.

In the smartphone, there is a specific parameter called "SIM management" to assign data, voice, etc. to each SIM by default.

As I don't have a second SIM card, I can't test SMSSecure with 2 SIM cards...

Hope it helps you.

**Comment by c33s** [comment]
quite important would be to at least be able to select one sim which should be used.
currently, if you only have a sim card in slot 2 you are not able to send sms, because smssecure hardcoded tries to send with sim 1.

**Comment by BastienLQ** [comment]
@c33s SMSSecure uses the first SIM because that's how Android API is. Android < 5.1 doesn't have multi-SIM support and each phone have a custom API to work with 2 or more SIMs. So we're waiting for an upstream patch or a PR to add multi-SIM support in Android >= 5.1.

**Comment by djibux** [comment]
I would love dual SIM support.  It would be even better to associate contacts with a SIM card (typically I never send messages to my boss using my private number :))

**Comment by KallistiMan** [comment]
Fixed upstream in issue 555

**Comment by BastienLQ** [comment]
@KallistiMan I'm working on it. Will be available in `upstream` soon.

**Comment by flyinva** [comment]
I installed silence 0.14.3 from f-droid on dual SIM phone with cyanogenmod 13.

I see on wich SIM the message is received but can't find any way to choose wich SIM will be used for sending. All SMS are sent with first SIM.

**Comment by BastienLQ** [comment]
@flyinva Long-press on the send button should display every SIM card.

**Comment by maverick74** [comment]
@BLeQuerrec In what version of Silence is that???

I'm asking this because the Google Play version shows me option to send Secure/Insecure SMS
The Latest beta does not show anything :(

Help Please

**Comment by maverick74** [comment]
Forget it. I just found that prior to 5.1 multi sim is not supported. This will keep me from using it on my wiko darkmoon :(
