### ISSUE TITLE
SMS Phishing

### ISSUE THREAD

**Issue by der-stefan** [SMSSecure/SMSSecure#88]
Is there any way, my mobile number gets commited to the internet?
Since using SMSsecure, I received several phishing SMS. A friend of mine experiences the same. We both installed SMSsecure at the beginning of April 2015 (Version 0.5.1, now 0.5.3) and never had any Spam SMS before.
The sms came from a number starting with +44.

Is it the NSA that is angry about our encryption? Is it my provider that just now sold my telephone number to the devil? Or is it SMSsecure? At least someone wants to identify myself.

I really like it to encrypt SMS, even though keys are short and SMS content shrinks.

**Comment by BastienLQ** [comment]
It is a coincidence: SMSSecure doesn't use Internet, except for receiving MMS through proxy, and phone number isn't registered.

**Comment by der-stefan** [comment]
Thank you for your reply. I am no conspiracist and I am severely concerned by this.
But let's keep on going.

**Comment by BastienLQ** [comment]
I understand. But it can't be SMSSecure, and your the only user that complains about this.
