### ISSUE TITLE
Maybe merging this pr to fix an issue

### ISSUE THREAD

**Issue by AlexAlexandru** [SMSSecure/SMSSecure#89]
How about merging this pr https://github.com/WhisperSystems/TextSecure/pull/2776

**Comment by pR0Ps** [comment]
I'd like to look into why it wasn't merged by TextSecure before pulling it in, but on first glace it looks fine.

**Comment by pR0Ps** [comment]
I spoke with one of the TextSecure devs, he said the issue has been fixed in a separate commit.

We've already pulled this fix in as part of #57 and will push it into the main branch once the Proguard test failures are fixed.
