### ISSUE TITLE
First run tutorial

### ISSUE THREAD

**Issue by BastienLQ** [SMSSecure/SMSSecure#90]

**Comment by pR0Ps** [comment]
Looking into using https://github.com/amlcurran/ShowcaseView/

**Comment by SecUpwN** [comment]
Just wanted to digg a little deeper into how to best implement `ShowcaseView` for [our Issue 181](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/181) when I noticed that [ShowcaseView is deprecated](https://github.com/amlcurran/ShowcaseView#showcaseview-is-deprecated) and that its developer wants to re-write the project from scratch for far better support. I have emailed him asking for where the new project is, update will follow.

**Comment by pR0Ps** [comment]
Implemented in #260
