### ISSUE TITLE
Change the main UI colour to be something different from TextSecure

### ISSUE THREAD

**Issue by bungabunga** [SMSSecure/SMSSecure#97]
I guess that many people will have TextSecure and SMSSecure both installed on their devices. They'll use SMSSecure as a secure SMS messenger and TextSecure for secure push messages. Because of very similar UI i suggest SMSSecure to cahnge TextSecure blue UI colour to something else to avoid further confusion.

The new colour should not be too agressive (red, yellow, orange...) but something eye friendly:
- different shade of blue
- green (TS used to be green as a SMS only application)
- a very mild purple (similar to a new logo)

**Comment by pR0Ps** [comment]
Will be done as part of #51
