### ISSUE TITLE
Conversation view not loaded after sending new sms

### ISSUE THREAD

**Issue by dmgawel** [SMSSecure/SMSSecure#99]
After sending new sms that starts new thread (no thread with recipient existed before sending sms) message is not displayed. You have to re-enter this thread.

Device info: Motorola Moto E 2015, android 5.0.2, SMSSecure 0.5.3

**Comment by pR0Ps** [comment]
Can you post more specific steps to reproduce? Are these secure conversations?

What I tried:
 - Hit the new message icon, pick a contact, send a message.
 - Hit the overflow menu, hit new group, select a single person, send a message.

In both cases, I immediately see my message in the thread.

**Comment by dmgawel** [comment]
Case scenario:
* get a call from unknown person (number does not exists in your contacts list)
* use "last calls" android view, tap his avatar and then tap message icon
* write and send sms

**Comment by pR0Ps** [comment]
Can't reproduce and there have been a ton of changes since this was opened.

@dmgawel : If you can still reproduce this bug with the latest version please reopen.
